"""Front G gate table: detected minus manual label, every boundary, 12 synthetic cases.

Uses the SAME comparison the timing test uses
(tests/synthetic/test_synthetic_lifecycles.boundary_deviations), so the table
cannot drift from what the suite asserts. Writes front_g_synthetic_deviations.md
next to this file.

    python research/labels/front_g/front_g_deviation_table.py
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

import numpy as np, pandas as pd, scipy  # noqa: E402,E401

from tests.synthetic.cases import CASES  # noqa: E402
from tests.synthetic.test_synthetic_lifecycles import (  # noqa: E402
    _labels_core, boundary_deviations, labelled_case)

OUT = Path(__file__).with_name("front_g_synthetic_deviations.md")


def main() -> int:
    lc = _labels_core()
    lines = [
        "# Front G — synthetic suite vs manual labels, per boundary",
        "",
        f"Generated by `{Path(__file__).name}`. numpy {np.__version__}, "
        f"scipy {scipy.__version__}, pandas {pd.__version__}.",
        "",
        "`dev` = detected − label (steps, signed). `tol` = the case tolerance the "
        "suite asserts against (6). `slack` = tol − |dev|. `label_tol` = the "
        "labeller's own `tolerance_idx` for that boundary, and `slack_lt` = "
        "label_tol − |dev| (shown, NOT asserted). Boundary k ≥ 1; phase 0 is "
        "pinned at index 0 on both sides and is not a boundary.",
        "",
        "| case | id | mode | k | phase | label | detected | dev | tol | slack | label_tol | slack_lt | unsure |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    n_bound = n_low = n_lt_fail = 0
    low, notes = [], []
    for cid, case in CASES.items():
        oid = lc.opaque_synthetic_id(cid)
        mode = case.get("test_mode", "standard")
        labelled_case(cid)  # hash check
        rows, problem = boundary_deviations(cid, case.get("tolerance", 6))
        if problem:
            lines.append(f"| {cid} | {oid} | {mode} | — | — | — | — | — | — | — | — | — | — |")
            notes.append(f"- **{cid}** ({mode}): no deviation computable — {problem}.")
            continue
        for r in rows:
            n_bound += 1
            slt = r["label_tol"] - abs(r["dev"])
            n_lt_fail += slt < 0
            if r["slack"] <= 1:
                n_low += 1
                low.append(f"{cid} / {r['phase']} (k={r['k']}): dev {r['dev']:+d}, slack {r['slack']}")
            lines.append(
                f"| {cid} | {oid} | {mode} | {r['k']} | {r['phase']} | {r['label']} | "
                f"{r['detected']} | {r['dev']:+d} | {r['tol']} | {r['slack']} | "
                f"{r['label_tol']} | {slt} | {r['unsure']} |")
    lines += ["", f"Boundaries with a number: {n_bound}.",
              f"Slack ≤ 1 under tol=6: {n_low}" + (":" if low else "."), *[f"- {x}" for x in low],
              f"Boundaries that would FAIL if the label's own tolerance_idx were the margin: {n_lt_fail}/{n_bound}.",
              "", *notes, ""]
    OUT.write_text("\n".join(lines))
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
