"""Tests for the opt-in ``incipient_method="plateau"`` incipient rule.

Three groups:

1. **Default-behaviour regression.** ``determine_periods(series)`` with no
   arguments must be identical to ``develop-v2.1``. The baseline in
   ``tests/baselines/baseline_defaults_multitrack.csv`` was generated by
   running the unmodified ``develop-v2.1`` checkout (commit 01c4492) over six
   calibration tracks, so this is a genuine cross-version check, not a
   self-comparison.

2. **Plateau accuracy on synthetic ground truth**, under
   the preset appropriate to each case (clean vs noisy).

3. **False-positive guards and structural invariants.**

A note on the presets (measured 2026-09-04, recorded here because it bears on
how much these assertions prove). The suite holds two populations that need
DIFFERENT pre-processing, so each case runs under ``preset_for(case_id)``:

* ``SYNTHETIC_CLEAN_PRESET`` (Lanczos off, one Savgol pass) for the four
  noise-free cases -- sequence 3/3, no timing failures.
* ``SYNTHETIC_NOISY_PRESET`` (Lanczos on at cutoff_high=18, Savgol off) for the
  eight 2 %-noise cases -- sequence 6/8, no timing failures.

The first version of this preset turned pre-processing off entirely, on the
theory that these series are clean by construction. Measured, that fails on
**both** populations (clean 1/3, noisy 0/8): with no pre-processing the
derivative of a piecewise-analytic series has a kink at every segment join, and
the extra extrema fragment the phases. The noisy preset in particular trades
2/8 sequences for a measurable plateau; the full reasoning and the numbers are
in the presets' block comment in ``tests/synthetic/cases.py``.
"""

import warnings

import numpy as np
import pandas as pd
import pytest

from cyclophaser import determine_periods
from cyclophaser.determine_periods import periods_to_dict
from tests.synthetic.cases import (
    CASES, CLEAN_CASE_IDS, NOISY_CASE_IDS, PLATEAU_START_CASE_IDS,
    STEEP_START_CASE_IDS, SYNTHETIC_CLEAN_PRESET, SYNTHETIC_NOISY_PRESET,
    preset_for,
)
from tests.synthetic.generators import make_lifecycle_series

from pathlib import Path

_BASELINE = Path(__file__).parent / "baselines" / "baseline_defaults_multitrack.csv"
_CALIB = Path(__file__).parent / "calibration_data"

# Tolerance of the synthetic suite: 6 timesteps = 18 h at 3 h/step.
TOLERANCE = 6

# Ground-truth incipient boundary = the length of the leading 'Ic' segment.
# Only the cases whose segment list actually opens with an Ic segment have a
# checkable boundary; see section 5 of
# research/incipient_plateau/REPORT_incipient_characterisation.md.
DESIGNED_IC = {
    "ItMD_clean":            3,
    "IcItMD_residual_noisy": 3,
    "IcItMD_ItMD_noisy":     3,
    "IcItMD_residual_clean": 3,
    "IcIt_observational":    6,
}
# True negatives for the incipient phase.
#
# NOT "cases with no designed Ic segment" — that is the wrong ground truth, and
# visual inspection in the calibration app is what exposed it. The generator's
# `sine` ramp is a half-period cosine with zero derivative at its endpoints, so
# ANY series opening with a sine It/D segment starts flat and genuinely has an
# initial plateau; the suite's own expected_phases already contains 'incipient'
# in 9 of the 12 cases, five of them with no designed Ic segment. The only true
# negatives are the two cases built with a `linear` opening ramp — the shape the
# generator documents as existing to prevent exactly this. See the
# classification block in tests/synthetic/cases.py.
NO_IC = list(STEEP_START_CASE_IDS)


def _run(series, **kwargs):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return determine_periods(series, **kwargs)


def _leading_incipient_len(df):
    """Length of the incipient run that starts at t0 (0 if there is none).

    Deliberately anchored at t0: the plateau rule only ever writes a leading
    incipient phase, so an 'incipient' appearing mid-series is the pre-existing
    catch-all fillna and not something this feature controls.
    """
    inc = (df["periods"] == "incipient").to_numpy()
    if not inc.any() or not inc[0]:
        return 0
    return int(np.argmin(inc)) if not inc.all() else len(inc)


def _sequence(df):
    return " > ".join(dict.fromkeys(
        k.rstrip(" 0123456789").strip() for k in periods_to_dict(df)))


# ── 1. default-behaviour regression ──────────────────────────────────────────
def _baseline_tracks():
    b = pd.read_csv(_BASELINE, dtype={"track": str})
    return sorted(b["track"].unique())


@pytest.mark.parametrize("track", _baseline_tracks())
def test_defaults_identical_to_develop_v21(track):
    """determine_periods(series) with no args == develop-v2.1, per track."""
    baseline = pd.read_csv(_BASELINE, dtype={"track": str})
    expected = baseline[baseline["track"] == track].reset_index(drop=True)

    d = pd.read_csv(_CALIB / f"{track}.csv", sep=";", index_col="time",
                    parse_dates=True)
    df = _run(d["min_max_zeta_850"])

    got = pd.DataFrame({
        "time": [t.isoformat() for t in df.index],
        "periods": df["periods"].to_numpy(),
    })
    assert list(got["time"]) == list(expected["time"]), (
        f"{track}: time index differs from the develop-v2.1 baseline")
    assert list(got["periods"]) == list(expected["periods"]), (
        f"{track}: default phase labels differ from the develop-v2.1 baseline")


def test_defaults_unaffected_by_new_parameters_being_present():
    """Passing the plateau parameters at their DEFAULTS changes nothing."""
    d = pd.read_csv(_CALIB / "20150377.csv", sep=";", index_col="time",
                    parse_dates=True)
    series = d["min_max_zeta_850"]
    bare = _run(series)
    explicit = _run(series, incipient_method="geometric",
                    incipient_plateau_tau=0.20,
                    incipient_plateau_signal="derivative",
                    incipient_plateau_crossing="single",
                    incipient_plateau_k=3,
                    incipient_amplitude_fraction=0.15)
    pd.testing.assert_frame_equal(bare, explicit)


def test_threshold_incipient_length_is_ignored_under_plateau():
    """threshold_incipient_length must have no effect when method='plateau'."""
    series = CASES["IcItMD_residual_clean"]["series"]
    _p = preset_for("IcItMD_residual_clean")
    a = _run(series, **_p, incipient_method="plateau",
             threshold_incipient_length=0.1)
    b = _run(series, **_p, incipient_method="plateau",
             threshold_incipient_length=0.6)
    pd.testing.assert_frame_equal(a, b)

    # ... while it very much does have an effect under the geometric rule,
    # which is what makes the assertion above meaningful. Measured on a real
    # track under package defaults, where case B fires and the geometric
    # boundary genuinely tracks the threshold (5 -> 26 steps); the synthetic
    # series above are not a usable control here because their leading
    # incipient comes from the catch-all fillna, which the threshold does not
    # touch.
    d = pd.read_csv(_CALIB / "20150377.csv", sep=";", index_col="time",
                    parse_dates=True)["min_max_zeta_850"]
    g1 = _run(d, threshold_incipient_length=0.1)
    g2 = _run(d, threshold_incipient_length=0.6)
    assert _leading_incipient_len(g1) != _leading_incipient_len(g2)


# ── 2. plateau accuracy on synthetic ground truth ────────────────────────────
_VARIANTS = {
    "single_derivative":  dict(),
    "sustained_k3":       dict(incipient_plateau_crossing="sustained",
                               incipient_plateau_k=3),
    "vorticity_signal":   dict(incipient_plateau_signal="vorticity"),
}


_DERIV_VARIANTS = {k: v for k, v in _VARIANTS.items() if k != "vorticity_signal"}


@pytest.mark.parametrize("variant", sorted(_DERIV_VARIANTS))
@pytest.mark.parametrize("case_id", sorted(DESIGNED_IC))
def test_plateau_boundary_within_tolerance(case_id, variant):
    """The plateau boundary lands within the suite's tolerance of the known Ic."""
    gt = DESIGNED_IC[case_id]
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20,
              **_VARIANTS[variant])
    got = _leading_incipient_len(df)
    assert got > 0, f"{case_id} [{variant}]: no incipient phase was created"
    assert abs(got - gt) <= TOLERANCE, (
        f"{case_id} [{variant}]: boundary {got} vs ground truth {gt} "
        f"(error {got - gt:+d}, tolerance {TOLERANCE})")


@pytest.mark.parametrize(
    "case_id", sorted(set(DESIGNED_IC) & set(CLEAN_CASE_IDS)))
def test_plateau_vorticity_signal_on_clean_cases(case_id):
    """signal="vorticity" is accurate on clean series."""
    gt = DESIGNED_IC[case_id]
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20,
              incipient_plateau_signal="vorticity")
    got = _leading_incipient_len(df)
    assert got > 0, f"{case_id}: no incipient phase was created"
    assert abs(got - gt) <= TOLERANCE


@pytest.mark.parametrize(
    "case_id", sorted(set(DESIGNED_IC) & set(NOISY_CASE_IDS)))
def test_plateau_vorticity_signal_is_defeated_by_noise(case_id):
    """MEASURED LIMITATION of signal="vorticity" — pinned, not worked around.

    ``"vorticity"`` measures the slope on ``np.gradient`` of the UNFILTERED
    input. That is what makes it immune to Lanczos/Savgol edge artifacts, and it
    is exactly what exposes it to the raw noise: on the 2 %-noise cases the
    first sample of the normalised raw gradient is already 0.25-0.57, i.e. above
    any usable tau, so the plateau has zero length and no incipient phase is
    created. On the clean cases the same quantity is exactly 0.000.

    This is the whole trade-off of the ``incipient_plateau_signal`` toggle in
    one assertion, and it is a decision input for calibration: "vorticity" buys
    filter-artifact immunity at the price of noise immunity.
    """
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20,
              incipient_plateau_signal="vorticity")
    assert _leading_incipient_len(df) == 0


# ── 3. guards and structural invariants ──────────────────────────────────────
@pytest.mark.parametrize("variant", sorted(_VARIANTS))
@pytest.mark.parametrize("case_id", NO_IC)
def test_plateau_creates_no_incipient_on_steep_start_cases(case_id, variant):
    """Steep-start cases must not gain a substantial incipient phase.

    MEASURED LIMITATION, not a slack bound. These two are noisy cases, so they
    run under SYNTHETIC_NOISY_PRESET, whose Lanczos pass smooths their
    deliberately abrupt onset: normalised |dz| at the first sample falls from
    **0.94 / 0.66 on the raw series** to **0.147 / 0.150 after filtering** —
    below tau, so a 1-timestep incipient appears. That plateau is invented by
    the filter, not present in the data. The bound is set at what is measured,
    so a regression making it materially worse still fails.
    """
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20,
              **_VARIANTS[variant])
    got = _leading_incipient_len(df)
    assert got <= 1, (
        f"{case_id} [{variant}]: plateau invented a leading incipient phase "
        f"of {got} steps (measured limit: 1)")


@pytest.mark.parametrize("case_id", NO_IC)
def test_vorticity_signal_rejects_filter_invented_plateaus(case_id):
    """signal="vorticity" gets the steep-start cases exactly right.

    The other half of the ``incipient_plateau_signal`` trade-off, and the one
    that argues FOR "vorticity": reading the unfiltered series means the
    deliberately steep onset is still steep, so no incipient phase is created —
    whereas "derivative", measured after the Lanczos, sees the filter's own
    smoothing of that onset and emits a 1-step phase.
    """
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20,
              incipient_plateau_signal="vorticity")
    assert _leading_incipient_len(df) == 0


@pytest.mark.parametrize("case_id", sorted(PLATEAU_START_CASE_IDS))
def test_plateau_start_cases_do_get_an_incipient_phase(case_id):
    """Every flat-opening case gets an incipient phase — the positive control.

    Pins the observation that motivated the reclassification: an initial plateau
    is present in 10 of the 12 cases, designed Ic segment or not, so the plateau
    rule finding one there is correct behaviour, not over-detection.
    """
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="plateau", incipient_plateau_tau=0.20)
    assert _leading_incipient_len(df) > 0, (
        f"{case_id} opens with a flat ramp but got no incipient phase")



def test_plateau_boundary_helper_contract():
    """Unit-test the documented contract of the boundary helper directly."""
    from cyclophaser.find_stages import _incipient_plateau_boundary as B

    rel = np.array([0.0, 0.05, 0.1, 0.5, 0.9, 1.0, 0.2, 0.05])
    # single: first sample at or above tau
    assert B(rel, 0.20, "single", 3) == 3
    assert B(rel, 0.05, "single", 3) == 1
    # rel(0) already at/above tau -> zero-length plateau -> no incipient
    assert B(np.array([0.9, 0.1, 0.1, 1.0]), 0.20, "single", 3) == 0
    # sustained: needs k consecutive samples at or above tau
    spike = np.array([0.0, 0.9, 0.0, 0.0, 0.3, 0.4, 0.5, 1.0])
    assert B(spike, 0.20, "single", 3) == 1        # fooled by the lone spike
    assert B(spike, 0.20, "sustained", 3) == 4     # ignores it
    # no sustained run anywhere -> declines rather than falling back to single
    assert B(np.array([0.0, 1.0, 0.0, 1.0, 0.0]), 0.5, "sustained", 3) == 0
    # k longer than the series -> declines
    assert B(np.array([0.0, 1.0]), 0.5, "sustained", 5) == 0


def test_plateau_declines_when_first_sample_is_already_steep():
    """rel(0) >= tau is a zero-length plateau: no incipient phase.

    Uses a real track under package defaults, where the t0 edge artifact puts
    rel(0) at 0.833 — comfortably above tau=0.20. (A synthetic series is not
    usable here: its leading Ic segment has an exactly-zero derivative, so
    rel(0) == 0.0 and no tau above zero can trigger this path.)
    """
    d = pd.read_csv(_CALIB / "20190325.csv", sep=";", index_col="time",
                    parse_dates=True)["min_max_zeta_850"]
    df = _run(d, incipient_method="plateau", incipient_plateau_tau=0.20)
    assert _leading_incipient_len(df) == 0


def test_plateau_boundary_grows_monotonically_with_tau():
    """A larger tau can only push the plateau edge later, never earlier."""
    series = CASES["IcItMD_residual_clean"]["series"]
    _p = preset_for("IcItMD_residual_clean")
    lens = [
        _leading_incipient_len(
            _run(series, **_p, incipient_method="plateau",
                 incipient_plateau_tau=t))
        for t in (0.05, 0.10, 0.15, 0.20, 0.30)
    ]
    assert lens == sorted(lens), f"non-monotonic boundary vs tau: {lens}"


# It -> D -> It: the pattern the geometric case-A branch was written for.
_SEG_ITDIT = [
    {"type": "It", "n": 12, "shape": "sine"},
    {"type": "D",  "n": 10, "shape": "sine"},
    {"type": "It", "n": 18, "shape": "sine"},
    {"type": "M",  "n": 4,  "shape": "plateau"},
    {"type": "D",  "n": 22, "shape": "sine"},
]


def test_plateau_does_not_break_the_it_d_it_pattern():
    """An It->D->It series survives the plateau rule intact.

    Measured note: the geometric case-A branch (``phases_order[:3] ==
    ['intensification', 'decay', 'intensification']``) is never actually
    reached, here or on any of the 51 calibration tracks. The reason is the
    property asserted by the ``quase_ItD`` case: a smooth It->D transition must
    pass through a local vorticity minimum, which is detected as ``mature``, so
    the order is always ``[It, M, D, It, M, D]`` and never ``[It, D, It]``.
    This test therefore asserts what is actually observable — that the plateau
    rule leaves the two-cycle structure exactly as the geometric rule detects it
    — rather than pretending to exercise a dead branch.
    """
    series = make_lifecycle_series(_SEG_ITDIT, noise_frac=0.0)
    # noise_frac=0.0 -> the clean preset is the right one for this series.
    geo = _run(series, **SYNTHETIC_CLEAN_PRESET)
    plat = _run(series, **SYNTHETIC_CLEAN_PRESET,
                incipient_method="plateau", incipient_plateau_tau=0.20)

    # The plateau rule may legitimately shorten or drop the LEADING incipient
    # phase -- that is the whole point of it. What it must not do is disturb the
    # It->D->It structure that follows. So the assertion is on everything past
    # the boundary, plus the presence of the pattern itself.
    b = max(_leading_incipient_len(geo), _leading_incipient_len(plat))
    assert list(geo["periods"][b:]) == list(plat["periods"][b:]), (
        f"plateau altered labels beyond the incipient boundary "
        f"({_sequence(geo)} -> {_sequence(plat)})")
    for phase in ("intensification", "decay"):
        assert phase in _sequence(plat), (
            f"plateau lost the {phase} phase: {_sequence(plat)}")
    # Nothing but the incipient phase may differ anywhere in the series.
    diff = [(g, q) for g, q in zip(geo["periods"], plat["periods"]) if g != q]
    assert all("incipient" in (g, q) for g, q in diff), (
        f"plateau changed non-incipient labels: {set(diff)}")


# ── parameter validation ─────────────────────────────────────────────────────
@pytest.mark.parametrize("kwargs", [
    dict(incipient_method="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_signal="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_crossing="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_tau=0.0),
    dict(incipient_method="plateau", incipient_plateau_tau=1.5),
    dict(incipient_method="plateau", incipient_plateau_crossing="sustained",
         incipient_plateau_k=0),
    dict(incipient_method="amplitude", incipient_amplitude_fraction=0.0),
    dict(incipient_method="amplitude", incipient_amplitude_fraction=1.5),
    dict(incipient_method="amplitude", incipient_amplitude_fraction=-0.1),
])
def test_invalid_parameters_raise(kwargs):
    with pytest.raises(ValueError):
        _run(CASES["ItMD_clean"]["series"], **kwargs)


# ═════════════════════════════════════════════════════════════════════════════
# 4. incipient_method="amplitude"
# ═════════════════════════════════════════════════════════════════════════════
# The level-based analogue of mature_method="amplitude": the incipient phase
# lasts until the first deepening is `incipient_amplitude_fraction` complete.
#
# Fraction that the ground truth actually implies (measured: the fraction of the
# first leg's amplitude already covered AT the designed Ic boundary, and at
# boundary + tolerance):
#
#     case                     frac@gt   frac@(gt+6)
#     ItMD_clean                 0.009        0.196
#     IcItMD_residual_clean      0.018        0.315
#     IcItMD_residual_noisy      0.035        0.336
#     IcItMD_ItMD_noisy          0.063        0.503
#     IcIt_observational         0.000        0.026
#
# So the synthetic ground truth is satisfied by a fraction well BELOW the 0.15
# default, and IcIt_observational -- a truncated series whose first leg is the
# whole 65 steps, so any fraction of it is many timesteps -- binds hardest at
# 0.026. The default is left at 0.15 deliberately: it is the author's to
# calibrate visually, not this suite's to pin.
_AMP_ACCURATE = sorted(set(DESIGNED_IC) - {"IcIt_observational"})


@pytest.mark.parametrize("fraction", [0.05, 0.10])
@pytest.mark.parametrize("case_id", _AMP_ACCURATE)
def test_amplitude_boundary_within_tolerance(case_id, fraction):
    """Amplitude boundary lands within the suite's tolerance of the known Ic."""
    gt = DESIGNED_IC[case_id]
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="amplitude",
              incipient_amplitude_fraction=fraction)
    got = _leading_incipient_len(df)
    assert got > 0, f"{case_id} [f={fraction}]: no incipient phase was created"
    assert abs(got - gt) <= TOLERANCE, (
        f"{case_id} [f={fraction}]: boundary {got} vs ground truth {gt} "
        f"(error {got - gt:+d}, tolerance {TOLERANCE})")


def test_amplitude_needs_a_small_fraction_on_a_truncated_series():
    """MEASURED PROPERTY: the boundary scales with the FIRST LEG, not the series.

    ``IcIt_observational`` is Ic(6) followed by an It that never reaches peak,
    so its first z extremum is the last sample and the "first deepening" spans
    the whole 65-step series. A fraction of that is many timesteps: at the 0.15
    default the boundary lands at 21 against a ground truth of 6. The ground
    truth is reached only for a fraction at or below ~0.026.

    Pinned because it is a decision input for calibration, not a defect: it says
    the fraction is not scale-free across life-cycle shapes the way tau is.
    """
    case_id = "IcIt_observational"
    gt = DESIGNED_IC[case_id]
    at_default = _leading_incipient_len(
        _run(CASES[case_id]["series"], **preset_for(case_id),
             incipient_method="amplitude", incipient_amplitude_fraction=0.15))
    assert at_default - gt > TOLERANCE, (
        "the 0.15 default no longer overshoots this truncated case; the note "
        "above and the calibration guidance need re-measuring")

    at_small = _leading_incipient_len(
        _run(CASES[case_id]["series"], **preset_for(case_id),
             incipient_method="amplitude", incipient_amplitude_fraction=0.02))
    assert abs(at_small - gt) <= TOLERANCE


@pytest.mark.parametrize("case_id", NO_IC)
def test_amplitude_does_not_reject_steep_start_cases(case_id):
    """STRUCTURAL DIFFERENCE from plateau, pinned so the A/B is read correctly.

    The plateau rule has a rejection mechanism: rel(0) >= tau means a zero-length
    plateau and no incipient phase. The amplitude rule has none, and cannot have
    one by construction -- |z(t) - z(t0)| starts at exactly 0 for every series,
    so some prefix always falls below any positive fraction. A LINEAR opening
    ramp covers fraction f of its leg after about f x leg_length steps, so these
    two deliberately steep-onset cases still receive a short incipient phase
    (measured: 3 steps at the 0.15 default) rather than none.

    Consequence: on the 51 real tracks the amplitude method returns a boundary
    on 51/51 -- it declines on 0 -- whereas geometric gives one on 48/51. The
    method is not a false-positive filter; it is a rescaling of where the phase
    ends. That is the thing to weigh in the visual A/B against plateau.
    """
    got = _leading_incipient_len(
        _run(CASES[case_id]["series"], **preset_for(case_id),
             incipient_method="amplitude", incipient_amplitude_fraction=0.15))
    assert got > 0


@pytest.mark.parametrize("case_id", sorted(PLATEAU_START_CASE_IDS))
def test_amplitude_gives_every_flat_start_an_incipient_phase(case_id):
    """Positive control, mirroring the plateau one."""
    df = _run(CASES[case_id]["series"], **preset_for(case_id),
              incipient_method="amplitude", incipient_amplitude_fraction=0.15)
    assert _leading_incipient_len(df) > 0


def test_amplitude_boundary_grows_with_fraction():
    """LARGER fraction -> LONGER incipient phase.

    The direction is the OPPOSITE of mature_amplitude_fraction's, so this guards
    against the sense being inverted by analogy.
    """
    series = CASES["IcItMD_residual_clean"]["series"]
    _p = preset_for("IcItMD_residual_clean")
    lens = [
        _leading_incipient_len(
            _run(series, **_p, incipient_method="amplitude",
                 incipient_amplitude_fraction=f))
        for f in (0.05, 0.10, 0.15, 0.25, 0.40)
    ]
    assert lens == sorted(lens), f"non-monotonic boundary vs fraction: {lens}"
    assert lens[-1] > lens[0], f"fraction had no effect: {lens}"


def test_amplitude_ignores_threshold_and_plateau_parameters():
    """Mutual exclusion, the analogue of threshold_mature_length under amplitude."""
    series = CASES["IcItMD_residual_clean"]["series"]
    _p = preset_for("IcItMD_residual_clean")
    base = _run(series, **_p, incipient_method="amplitude")
    for kwargs in (
        dict(threshold_incipient_length=0.6),
        dict(incipient_plateau_tau=0.45),
        dict(incipient_plateau_signal="vorticity"),
        dict(incipient_plateau_crossing="sustained", incipient_plateau_k=7),
    ):
        other = _run(series, **_p, incipient_method="amplitude", **kwargs)
        pd.testing.assert_frame_equal(base, other, obj=f"amplitude + {kwargs}")


def test_amplitude_reference_skips_degenerate_extrema():
    """The amplitude reference must ignore numerically negligible extrema.

    find_peaks_valleys uses >=/<= so that flat plateaux are detected, which marks
    micro-wiggles inside a flat opening as extrema: ItMD_clean carries a 'peak'
    at index 1 whose |z - z[t0]| is 1e-4 of the series range. Taking that as the
    amplitude reference pinned the boundary at 1 regardless of the fraction,
    which is what this guard fixes -- so the boundary must now respond to the
    fraction on exactly that case.
    """
    series = CASES["ItMD_clean"]["series"]
    _p = preset_for("ItMD_clean")
    small = _leading_incipient_len(
        _run(series, **_p, incipient_method="amplitude",
             incipient_amplitude_fraction=0.05))
    large = _leading_incipient_len(
        _run(series, **_p, incipient_method="amplitude",
             incipient_amplitude_fraction=0.40))
    assert large > small > 0


def test_amplitude_does_not_break_the_it_d_it_pattern():
    """Case A: an It->D->It series survives the amplitude rule intact."""
    series = make_lifecycle_series(_SEG_ITDIT, noise_frac=0.0)
    geo = _run(series, **SYNTHETIC_CLEAN_PRESET)
    amp = _run(series, **SYNTHETIC_CLEAN_PRESET, incipient_method="amplitude",
               incipient_amplitude_fraction=0.15)
    b = max(_leading_incipient_len(geo), _leading_incipient_len(amp))
    assert list(geo["periods"][b:]) == list(amp["periods"][b:]), (
        f"amplitude altered labels beyond the incipient boundary "
        f"({_sequence(geo)} -> {_sequence(amp)})")
    for phase in ("intensification", "decay"):
        assert phase in _sequence(amp), f"amplitude lost {phase}: {_sequence(amp)}"
    diff = [(g, q) for g, q in zip(geo["periods"], amp["periods"]) if g != q]
    assert all("incipient" in (g, q) for g, q in diff), (
        f"amplitude changed non-incipient labels: {set(diff)}")
