"""Tests for the opt-in ``incipient_method="plateau"`` incipient rule.

Three groups:

1. **Default-behaviour regression.** ``determine_periods(series)`` with no
   arguments must be identical to ``develop-v2.1``. The baseline in
   ``tests/baselines/baseline_defaults_multitrack.csv`` was generated by
   running the unmodified ``develop-v2.1`` checkout (commit 01c4492) over six
   calibration tracks, so this is a genuine cross-version check, not a
   self-comparison.

2. **Plateau accuracy on synthetic ground truth**, under
   ``SYNTHETIC_VALIDATION_PRESET``.

3. **False-positive guards and structural invariants.**

A note on the preset (measured 2026-09-04, recorded here because it bears on
how much these assertions prove): ``SYNTHETIC_VALIDATION_PRESET`` disables both
the Lanczos filter and the Savitzky-Golay smoothing. Each half on its own is
harmless — with only ``use_filter=False``, or only ``use_smoothing=False``, the
synthetic suite's phase sequences are unchanged from the defaults. Turning both
off together, however, degrades the detected *sequence* on 5 of the 6 cases the
suite currently gets right (e.g. ``ItMD_clean`` collapses to
``incipient > decay``): with no pre-processing at all, the derivative of these
piecewise-analytic series has a kink at every segment join, and the extra
extrema fragment the phases. The assertions below therefore check the
**incipient boundary only** — the quantity this feature actually defines. The
full-sequence assertions remain in ``test_synthetic_lifecycles.py``, which runs
under package defaults and is untouched.
"""

import warnings

import numpy as np
import pandas as pd
import pytest

from cyclophaser import determine_periods
from cyclophaser.determine_periods import periods_to_dict
from tests.synthetic.cases import CASES, SYNTHETIC_VALIDATION_PRESET
from tests.synthetic.generators import make_lifecycle_series

from pathlib import Path

_BASELINE = Path(__file__).parent / "baselines" / "baseline_defaults_multitrack.csv"
_CALIB = Path(__file__).parent / "calibration_data"

# Tolerance of the synthetic suite: 6 timesteps = 18 h at 3 h/step.
TOLERANCE = 6

# Ground-truth incipient boundary = the length of the leading 'Ic' segment.
# Only the cases whose segment list actually opens with an Ic segment have a
# checkable boundary; see section 5 of
# research/incipient_plateau/REPORT_incipient_characterisation.md.
DESIGNED_IC = {
    "ItMD_clean":            3,
    "IcItMD_residual_noisy": 3,
    "IcItMD_ItMD_noisy":     3,
    "IcItMD_residual_clean": 3,
    "IcIt_observational":    6,
}
# Cases whose expected_phases contain no 'incipient' at all.
NO_IC = ["DItMD_noisy", "DItMD_residual_noisy"]


def _run(series, **kwargs):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return determine_periods(series, **kwargs)


def _leading_incipient_len(df):
    """Length of the incipient run that starts at t0 (0 if there is none).

    Deliberately anchored at t0: the plateau rule only ever writes a leading
    incipient phase, so an 'incipient' appearing mid-series is the pre-existing
    catch-all fillna and not something this feature controls.
    """
    inc = (df["periods"] == "incipient").to_numpy()
    if not inc.any() or not inc[0]:
        return 0
    return int(np.argmin(inc)) if not inc.all() else len(inc)


def _sequence(df):
    return " > ".join(dict.fromkeys(
        k.rstrip(" 0123456789").strip() for k in periods_to_dict(df)))


# ── 1. default-behaviour regression ──────────────────────────────────────────
def _baseline_tracks():
    b = pd.read_csv(_BASELINE, dtype={"track": str})
    return sorted(b["track"].unique())


@pytest.mark.parametrize("track", _baseline_tracks())
def test_defaults_identical_to_develop_v21(track):
    """determine_periods(series) with no args == develop-v2.1, per track."""
    baseline = pd.read_csv(_BASELINE, dtype={"track": str})
    expected = baseline[baseline["track"] == track].reset_index(drop=True)

    d = pd.read_csv(_CALIB / f"{track}.csv", sep=";", index_col="time",
                    parse_dates=True)
    df = _run(d["min_max_zeta_850"])

    got = pd.DataFrame({
        "time": [t.isoformat() for t in df.index],
        "periods": df["periods"].to_numpy(),
    })
    assert list(got["time"]) == list(expected["time"]), (
        f"{track}: time index differs from the develop-v2.1 baseline")
    assert list(got["periods"]) == list(expected["periods"]), (
        f"{track}: default phase labels differ from the develop-v2.1 baseline")


def test_defaults_unaffected_by_new_parameters_being_present():
    """Passing the plateau parameters at their DEFAULTS changes nothing."""
    d = pd.read_csv(_CALIB / "20150377.csv", sep=";", index_col="time",
                    parse_dates=True)
    series = d["min_max_zeta_850"]
    bare = _run(series)
    explicit = _run(series, incipient_method="geometric",
                    incipient_plateau_tau=0.20,
                    incipient_plateau_signal="derivative",
                    incipient_plateau_crossing="single",
                    incipient_plateau_k=3)
    pd.testing.assert_frame_equal(bare, explicit)


def test_threshold_incipient_length_is_ignored_under_plateau():
    """threshold_incipient_length must have no effect when method='plateau'."""
    series = CASES["IcItMD_residual_clean"]["series"]
    a = _run(series, **SYNTHETIC_VALIDATION_PRESET, incipient_method="plateau",
             threshold_incipient_length=0.1)
    b = _run(series, **SYNTHETIC_VALIDATION_PRESET, incipient_method="plateau",
             threshold_incipient_length=0.6)
    pd.testing.assert_frame_equal(a, b)

    # ... while it very much does have an effect under the geometric rule,
    # which is what makes the assertion above meaningful. Measured on a real
    # track under package defaults, where case B fires and the geometric
    # boundary genuinely tracks the threshold (5 -> 26 steps); the synthetic
    # series above are not a usable control here because their leading
    # incipient comes from the catch-all fillna, which the threshold does not
    # touch.
    d = pd.read_csv(_CALIB / "20150377.csv", sep=";", index_col="time",
                    parse_dates=True)["min_max_zeta_850"]
    g1 = _run(d, threshold_incipient_length=0.1)
    g2 = _run(d, threshold_incipient_length=0.6)
    assert _leading_incipient_len(g1) != _leading_incipient_len(g2)


# ── 2. plateau accuracy on synthetic ground truth ────────────────────────────
_VARIANTS = {
    "single_derivative":  dict(),
    "sustained_k3":       dict(incipient_plateau_crossing="sustained",
                               incipient_plateau_k=3),
    "vorticity_signal":   dict(incipient_plateau_signal="vorticity"),
}


@pytest.mark.parametrize("variant", sorted(_VARIANTS))
@pytest.mark.parametrize("case_id", sorted(DESIGNED_IC))
def test_plateau_boundary_within_tolerance(case_id, variant):
    """The plateau boundary lands within the suite's tolerance of the known Ic."""
    gt = DESIGNED_IC[case_id]
    df = _run(CASES[case_id]["series"], **SYNTHETIC_VALIDATION_PRESET,
              incipient_method="plateau", incipient_plateau_tau=0.20,
              **_VARIANTS[variant])
    got = _leading_incipient_len(df)
    assert got > 0, f"{case_id} [{variant}]: no incipient phase was created"
    assert abs(got - gt) <= TOLERANCE, (
        f"{case_id} [{variant}]: boundary {got} vs ground truth {gt} "
        f"(error {got - gt:+d}, tolerance {TOLERANCE})")


# ── 3. guards and structural invariants ──────────────────────────────────────
@pytest.mark.parametrize("variant", sorted(_VARIANTS))
@pytest.mark.parametrize("case_id", NO_IC)
def test_plateau_creates_no_incipient_on_no_ic_cases(case_id, variant):
    """Cases designed without an incipient must not gain a leading one."""
    df = _run(CASES[case_id]["series"], **SYNTHETIC_VALIDATION_PRESET,
              incipient_method="plateau", incipient_plateau_tau=0.20,
              **_VARIANTS[variant])
    assert _leading_incipient_len(df) == 0, (
        f"{case_id} [{variant}]: plateau invented a leading incipient phase "
        f"of {_leading_incipient_len(df)} steps")


def test_plateau_boundary_helper_contract():
    """Unit-test the documented contract of the boundary helper directly."""
    from cyclophaser.find_stages import _incipient_plateau_boundary as B

    rel = np.array([0.0, 0.05, 0.1, 0.5, 0.9, 1.0, 0.2, 0.05])
    # single: first sample at or above tau
    assert B(rel, 0.20, "single", 3) == 3
    assert B(rel, 0.05, "single", 3) == 1
    # rel(0) already at/above tau -> zero-length plateau -> no incipient
    assert B(np.array([0.9, 0.1, 0.1, 1.0]), 0.20, "single", 3) == 0
    # sustained: needs k consecutive samples at or above tau
    spike = np.array([0.0, 0.9, 0.0, 0.0, 0.3, 0.4, 0.5, 1.0])
    assert B(spike, 0.20, "single", 3) == 1        # fooled by the lone spike
    assert B(spike, 0.20, "sustained", 3) == 4     # ignores it
    # no sustained run anywhere -> declines rather than falling back to single
    assert B(np.array([0.0, 1.0, 0.0, 1.0, 0.0]), 0.5, "sustained", 3) == 0
    # k longer than the series -> declines
    assert B(np.array([0.0, 1.0]), 0.5, "sustained", 5) == 0


def test_plateau_declines_when_first_sample_is_already_steep():
    """rel(0) >= tau is a zero-length plateau: no incipient phase.

    Uses a real track under package defaults, where the t0 edge artifact puts
    rel(0) at 0.833 — comfortably above tau=0.20. (A synthetic series is not
    usable here: its leading Ic segment has an exactly-zero derivative, so
    rel(0) == 0.0 and no tau above zero can trigger this path.)
    """
    d = pd.read_csv(_CALIB / "20190325.csv", sep=";", index_col="time",
                    parse_dates=True)["min_max_zeta_850"]
    df = _run(d, incipient_method="plateau", incipient_plateau_tau=0.20)
    assert _leading_incipient_len(df) == 0


def test_plateau_boundary_grows_monotonically_with_tau():
    """A larger tau can only push the plateau edge later, never earlier."""
    series = CASES["IcItMD_residual_clean"]["series"]
    lens = [
        _leading_incipient_len(
            _run(series, **SYNTHETIC_VALIDATION_PRESET,
                 incipient_method="plateau", incipient_plateau_tau=t))
        for t in (0.05, 0.10, 0.15, 0.20, 0.30)
    ]
    assert lens == sorted(lens), f"non-monotonic boundary vs tau: {lens}"


# It -> D -> It: the pattern the geometric case-A branch was written for.
_SEG_ITDIT = [
    {"type": "It", "n": 12, "shape": "sine"},
    {"type": "D",  "n": 10, "shape": "sine"},
    {"type": "It", "n": 18, "shape": "sine"},
    {"type": "M",  "n": 4,  "shape": "plateau"},
    {"type": "D",  "n": 22, "shape": "sine"},
]


def test_plateau_does_not_break_the_it_d_it_pattern():
    """An It->D->It series survives the plateau rule intact.

    Measured note: the geometric case-A branch (``phases_order[:3] ==
    ['intensification', 'decay', 'intensification']``) is never actually
    reached, here or on any of the 51 calibration tracks. The reason is the
    property asserted by the ``quase_ItD`` case: a smooth It->D transition must
    pass through a local vorticity minimum, which is detected as ``mature``, so
    the order is always ``[It, M, D, It, M, D]`` and never ``[It, D, It]``.
    This test therefore asserts what is actually observable — that the plateau
    rule leaves the two-cycle structure exactly as the geometric rule detects it
    — rather than pretending to exercise a dead branch.
    """
    series = make_lifecycle_series(_SEG_ITDIT, noise_frac=0.0)
    geo = _run(series, **SYNTHETIC_VALIDATION_PRESET)
    plat = _run(series, **SYNTHETIC_VALIDATION_PRESET,
                incipient_method="plateau", incipient_plateau_tau=0.20)

    assert _sequence(plat) == _sequence(geo), (
        f"plateau changed the sequence: {_sequence(geo)} -> {_sequence(plat)}")
    assert "intensification" in _sequence(plat)
    assert "decay" in _sequence(plat)
    # Only the leading phase may move; nothing after the incipient boundary
    # is allowed to change.
    b = max(_leading_incipient_len(geo), _leading_incipient_len(plat))
    assert list(geo["periods"][b:]) == list(plat["periods"][b:]), (
        "plateau altered labels beyond the incipient boundary")


# ── parameter validation ─────────────────────────────────────────────────────
@pytest.mark.parametrize("kwargs", [
    dict(incipient_method="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_signal="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_crossing="nonsense"),
    dict(incipient_method="plateau", incipient_plateau_tau=0.0),
    dict(incipient_method="plateau", incipient_plateau_tau=1.5),
    dict(incipient_method="plateau", incipient_plateau_crossing="sustained",
         incipient_plateau_k=0),
])
def test_invalid_parameters_raise(kwargs):
    with pytest.raises(ValueError):
        _run(CASES["ItMD_clean"]["series"], **kwargs)
