#!/usr/bin/env python
"""Passo 5, E4 — absolute local paths in versioned files (read-only).

    python research/cleanup/passo5/abs_paths.py LABEL   # writes LABEL.json / LABEL.md next to it

An occurrence is a line of a tracked text file (`git grep -I`) containing
`/Users/`, `/home/` or `C:\\`. Each is classified:
* `allowed` — in research/cleanup/, where the path was already replaced by a
  marker (<repo>, <env>, <tmp>, ~, <docs-venv>, <worktree...>) and what is left of
  the line does not identify the machine (no user name after /Users/ or /home/);
* `occurrence` — everything else (what E4 counts).
The lines themselves are not copied into the output (they would re-publish the
path); only file, line number and the matched prefix with the next path segment
masked.
"""
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PAT = re.compile(r"/Users/|/home/|C:\\\\")
USER = re.compile(r"(/Users/|/home/)([A-Za-z0-9._-]+)")


def main():
    label = sys.argv[1]
    out = subprocess.run(["git", "grep", "-I", "-n", "-E", r"/Users/|/home/|C:\\\\"], cwd=ROOT,
                         capture_output=True, text=True).stdout.splitlines()
    rows = []
    for o in out:
        f, n, text = o.split(":", 2)
        if not PAT.search(text):
            continue
        names = {m.group(2) for m in USER.finditer(text)}
        identifying = bool(names - {"<user>", "user", "you", "username", "runner", "..."})
        allowed = f.startswith("research/cleanup/") and not identifying
        rows.append(dict(file=f, line=int(n), kind="allowed" if allowed else "occurrence",
                         identifying=identifying))
    occ = [r for r in rows if r["kind"] == "occurrence"]
    by_file = Counter(r["file"] for r in occ)
    res = dict(label=label, occurrences=len(occ), allowed=len(rows) - len(occ), by_file=dict(by_file), rows=rows)
    (Path(__file__).with_name(f"{label}.json")).write_text(json.dumps(res, indent=1))
    md = [f"# {label} — absolute paths in versioned files (generated by abs_paths.py)\n",
          f"Occurrences (E4 counts these): **{len(occ)}** in {len(by_file)} files; allowed (research/cleanup/, "
          f"already marked): {len(rows) - len(occ)}.\n", "| file | occurrences |", "|---|---|"]
    md += [f"| `{f}` | {k} |" for f, k in sorted(by_file.items())]
    (Path(__file__).with_name(f"{label}.md")).write_text("\n".join(md) + "\n")
    print(md[1])
    for f, k in sorted(by_file.items()):
        print(f"  {k:4d}  {f}")


if __name__ == "__main__":
    main()
