version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout

      - run:
          name: Install build tools
          command: pip install --upgrade pip build

      - run:
          name: Build sdist and wheel
          command: python -m build

      - run:
          name: Install package from wheel
          command: pip install dist/*.whl

      - run:
          name: Install test dependencies
          command: pip install pytest

      - run:
          name: Run tests
          command: python -m pytest

      - store_test_results:
          path: test-reports

      - persist_to_workspace:
          root: .
          paths:
            - dist

  test_pypi_publish:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install twine
          command: pip install twine

      - run:
          name: Check distribution
          command: twine check dist/*

      - run:
          name: Publish to TestPyPI
          command: twine upload -u ${TESTPY_LOGIN} -p ${TESTPY_PASSWORD} --repository testpypi dist/* --verbose

  pypi_publish:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install twine
          command: pip install twine

      - run:
          name: Check distribution
          command: twine check dist/*

      - run:
          name: Publish to PyPI
          command: twine upload dist/* --verbose

workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
