#!/usr/bin/env python
"""Passo 6b — renders item 32 of docs/future_work.md (the clean-up front) from the
front's committed outputs. Every number in the item is read here from a file of
research/cleanup/ (or the git refs), with an assertion where it is parsed from
text; none is typed into the template.

    python research/cleanup/passo6/future_work_item32.py            # writes future_work_item32.md next to it
    python research/cleanup/passo6/future_work_item32.py --insert   # and inserts it into docs/future_work.md
    python research/cleanup/passo6/future_work_item32.py --replace  # re-renders item 32 in place (only item 32)

--insert adds the item after the last item (item 31) and before the closing
"## Note" section, which is not an item; no earlier line is edited. It refuses
if an item 32 already exists.
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
CLEAN = HERE.parent
ROOT = HERE.parents[2]


def j(rel):
    return json.loads((CLEAN / rel).read_text())


def grab(rel, pattern, group=1):
    """The `group` of the single line of `rel` that matches `pattern`."""
    hits = [m for m in (re.search(pattern, ln) for ln in (CLEAN / rel).read_text().splitlines()) if m]
    assert len(hits) == 1, (rel, pattern, len(hits))
    return hits[0].group(group)


def where_count(rows, prefix):
    return sum(1 for r in rows if r["where"].startswith(prefix))


# --- passo 1: C1 ---
hyg = j("passo1/hygiene_train.json")["summary"]
mech = j("passo1/refusal_mechanism.json")["grid"]
ptd = j("passo1/params_track_vs_defaults.json")
assert ptd["identical_bytes"] and ptd["sha256_params15_before"] == ptd["sha256_params_track_after"]
p4_pred = grab("passo1/PREVISOES.md", r"^\| P4 \| .*?: (\d+) sob o novo default")
digest_pre = grab("passo1/RELATORIO.md", r"^\| P1 \|.*\| pré `([0-9a-f]{8})…`")
digest_post = grab("passo1/RELATORIO.md", r"^\| P1 \|.*pós `([0-9a-f]{8})…`")
n = hyg["n_train"]

# --- passo 3: removals ---
tt = j("passo3/tag_and_trace.json")
removed = sum(1 for ln in (CLEAN / "passo3/removed_files.txt").read_text().splitlines() if ln.strip())
assert removed == tt["R2"]["checked"] == tt["R2"]["present_at_tag"]
r4_first = j("passo3/live_refs.json")
r4_corr = j("passo3/live_refs_2912b79_corrected.json")
r4_after = j("passo4/faseC_r4.json")

# --- passo 4 ---
d1_before = j("passo4/before.json")
d1_after = j("passo4/faseC_d1.json")
d2 = j("passo4/faseC_d2.json")
d3 = grab("passo4/RELATORIO_faseC.md", r"^\| D3 \|.*\| antes (\d+ erros / \d+ avisos) → depois (\d+ erros / \d+ avisos)", 0)
d3 = re.search(r"antes (\d+) erros / (\d+) avisos → depois (\d+) erros / (\d+) avisos", d3).groups()

# --- passo 5 ---
e1 = grab("passo5/RELATORIO.md", r"^\| E1 \|.*\| (\d+) passed / (\d+) failed \(todas", 0)
e1_failed = re.search(r"(\d+) passed / (\d+) failed \(todas", e1).group(2)
e1_second = re.search(r"segunda medição registrada ao lado: (\d+) passed / (\d+) failed",
                      (CLEAN / "passo5/RELATORIO.md").read_text()).groups()
e2_line = grab("passo5/RELATORIO.md", r"^\| E2 \|(.*)$")
e2_pred = re.search(r"(\d+) de ambiente, (\d+) de código \|", e2_line).groups()
e2_got = re.search(r"\*\*(\d+) de ambiente, (\d+) de código\*\*", e2_line).groups()
e2_pinned = re.search(r"fixado: (\d+) passed / (\d+) failed", e2_line).groups()
e4b, e4a = j("passo5/e4_before.json"), j("passo5/e4_after.json")
tid_b, tid_a = j("passo5/b_test_ids_before.json"), j("passo5/b_test_ids_after.json")
e5 = grab("passo5/RELATORIO.md", r"^\| E5 \|.*depois (\d+), dos quais (\d+);", 0)
e5 = re.search(r"depois (\d+), dos quais (\d+);", e5).groups()

# --- passo 6 ---
c21b, c21a = j("passo6/c21_scan_before.json"), j("passo6/c21_scan_after.json")
app_c21 = grab("passo6/c21_app_tests.txt", r"^(\d+) passed, \d+ warnings")
tags = j("passo6/tags.json")
dele = j("passo6/delete_6b.json")
post = j("passo6/post_6b.json")
del_remote = sum(l["deleted"] for l in dele["log"] if l["section"] == "remote")
del_local = sum(l["deleted"] for l in dele["log"] if l["section"] == "local_only")
not_deleted = [l["branch"] for l in dele["log"] if not l["deleted"]]
groups = Counter((l["section"], l["group"]) for l in dele["log"] if l["deleted"])
rtd = j("passo4/rtd_facts.json")
ci = grab("passo4/ci_python.md", r"Versions in the job that runs the tests: \['([0-9.]+)'\]")

T = []
w = T.append
w("## 32. Repository clean-up + `boundary_padding` default `\"reflect\"` (C1) — branch "
  "`chore/repo-cleanup`, **NOT merged**: the merge into `develop-v2.1` needs Danilo's separate authorisation")
w("")
w("**Every number below is regenerated by `research/cleanup/passo6/future_work_item32.py`** from the "
  "front's committed outputs under `research/cleanup/`. Per-step reports: `passo1/RELATORIO.md`, "
  "`passo3/RELATORIO.md`, `passo4/RELATORIO_faseC.md`, `passo5/RELATORIO.md`, `passo6/`; the final gate "
  "is `research/cleanup/RELATORIO_FINAL.md`, measured once after this item was committed. "
  "The inventory and the per-file decisions are in `research/cleanup/MANIFEST.md`.")
w("")
w("### Scope")
w("")
w("* **Passo 0–1.** Read-only inventory (files, branches, traceability), then C1 — the only "
  "behaviour change in `cyclophaser/` — and the params-15 → params-track rename.")
w("* **Passo 2.** `docs/findings.md`, one register of what the closed fronts established, refuted, "
  "decided and left open (§S01–§S12, every source `path:line@commit`).")
w("* **Passo 3.** Removal of the closed fronts' diagnostics, kept readable through an archive tag.")
w("* **Passo 4.** Documented defaults checked against the signatures; docstring/comment-only commits in "
  "`cyclophaser/`; the Read the Docs site rewritten; app texts.")
w("* **Passo 5.** Minor debts: app fixes, the evaluator's constant baselines, the digest generator opening "
  "training files only, absolute paths.")
w("* **Passo 6.** The branch table, archive tags for the branches that hold cited commits, and the "
  "deletion of the branches Danilo authorised by name.")
w("")
w("### C1 — `boundary_padding` default `\"reflect\"` (`742e685`)")
w("")
w("* **The default is the maintainer's choice (2026-09-28), made without a detection-quality "
  "measurement** (`CHANGELOG.md`, `[Unreleased]`). No score against labels was taken under it; the scores "
  "recorded for params-track were measured under `\"edge\"`.")
w(f"* **The two consequences expected when C1 was decided did not hold** on the {n} training series "
  f"(`passo1/hygiene_train.json`):")
w(f"  * no incipient refusals under `\"reflect\"` — predicted {p4_pred} (P4); measured "
  f"**{hyg['refusals']['default']}/{n}** under `\"reflect\"` and {hyg['refusals']['edge']}/{n} under "
  f"`\"edge\"`, the same series;")
w(f"  * defect I leaving the default path — it is present on **{hyg['defect_I']['default']}/{n}** under "
  f"`\"reflect\"` against {hyg['defect_I']['edge']}/{n} under `\"edge\"`.")
w(f"* Mechanism (post-hoc, `passo1/refusal_mechanism.json`): the default "
  f"`incipient_plateau_signal=\"vorticity\"` reads the plateau on the raw input, which the padding never "
  f"touches. Under `\"derivative\"` the padding decides: {mech['derivative/reflect']['n_refused']}/{n} "
  f"refusals under `\"reflect\"` against {mech['derivative/edge']['n_refused']}/{n} under `\"edge\"`.")
w(f"* What C1 moves: the final phase map on {hyg['maps_changed']}/{n} training series, the phase sequence "
  f"on {hyg['sequences_changed']}/{n}; the default-behaviour digest `{digest_pre}…` → `{digest_post}…`.")
w("")
w("### params-15 → params-track")
w("")
w(f"Renamed with `git mv`, byte-identical: sha256 `{ptd['sha256_params_track_after']}` before and after "
  f"(`passo1/params_track_vs_defaults.json`). It differs from the package defaults in "
  f"{len(ptd['differing'])} keys of {ptd['n_yaml_keys']}, `boundary_padding` among them. Historical "
  f"records keep the old name; dated correspondence notes were added.")
w("")
w("### Removals and the archive tag")
w("")
w(f"* `2912b79` removed **{removed}** files listed by `passo3/removal_list.py` from the MANIFEST; "
  f"{tt['R2']['present_at_tag']}/{tt['R2']['checked']} resolve through the annotated tag "
  f"**`archive/research-diagnostics-pre-cleanup`** (at `654a3e5`), as "
  f"`git show archive/research-diagnostics-pre-cleanup:<path>`.")
w(f"* One CSV was restored from the tag by `51596c0`, so {r4_after['removed']} of those paths are absent "
  f"from the tree.")
w("")
w("### `docs/findings.md`")
w("")
w(f"Built by `research/cleanup/passo2/make_findings.py` (`b60d57b`), maintained by hand since. §S10 maps every "
  f"removed file to where its finding is recorded ({tt['R3']['rows']} rows at passo 3, "
  f"{len(tt['R3']['failures'])} failures); §S11 lists every open item once; §S12 holds record corrections, "
  f"C1's premise among them.")
w("")
w("### Site rewrite and the new figure")
w("")
w("* `c1305af`: the Read the Docs pages rewritten for package users (approved by Danilo). `438eadf`: "
  "the generators in `docs/figures/` and their outputs in `docs/generated/` — the methodology figure "
  "(`make_methodology_figure.py`, panels A–K from the package's own output on a synthetic series, with an "
  "assertion that the replay of the public stage functions reproduces `get_periods`), the usage-guide "
  "figures on an hourly example track, and the default tables read from the signatures.")
w(f"* Documentation build, errors/warnings: {d3[0]}/{d3[1]} before → {d3[2]}/{d3[3]} after "
  f"(`passo4/RELATORIO_faseC.md`). `.readthedocs.yml` installs the package itself, so autodoc reads "
  f"the docstrings.")
w(f"* Documented defaults (`passo4/check_documented_defaults.py`): {d1_after['divergences']} divergences "
  f"in {d1_after['claims']} claims after the edits. Scores attributed to the current default "
  f"(`passo4/faseC_d2.json`): {d2['attributing']} of {d2['flagged']} reviewed lines.")
w("")
w("### App fixes")
w("")
w("* `bffa6fe`: every default the app writes, falls back to or states is read from the package signature; "
  "literal fallbacks removed; stale \"(default)\"/\"opt-in\" texts fixed.")
w("* `f00a7a0`: the Documentation tab replaced by a link to the site; switched-off checks exported as "
  "`null` in the YAML (before, the missing key took the package default, which is not off).")
w("* `bea55a6`: upload and dataset choice drawn inside the Calibration tab; Benchmark preset selection; "
  "ledger column renamed away from the refuted D2 metric; binary uploads refused; test-split ids removed "
  "from `tests/test_layer_inspector.py`; the Benchmark tests pass raw TRAIN ids.")
w("* `dbaacd6` (commit 21): a help text cited a test-split track; it now cites a training track "
  "(`passo6/rel_t0_window.py`, training files only).")
w(f"* App tests in the environment with the pinned versions of `requirements-app.txt`: "
  f"{e2_pinned[0]} passed / {e2_pinned[1]} failed (`passo5/RELATORIO.md`); after commit 21, "
  f"{app_c21} passed (`passo6/c21_app_tests.txt`).")
w("")
w("### Branch tags and branch deletion (passo 6)")
w("")
w(f"* {len(tags)} annotated tags `archive/<branch>` at the tips of the branches that hold commits cited "
  f"outside `develop-v2.1` (`passo6/tags.json`), pushed. `archive/exp/pre-peak-normalization` stays public "
  f"(Danilo, 2026-10-02).")
w(f"* Danilo authorised by name (2026-10-02) the branches of `passo6/removal_list.md` @ `fbeff00`. Each tip and "
  f"each group-B tag was checked before deletion (`passo6/delete_6b.py`); deleted **{del_remote} remote** "
  f"(A {groups[('remote', 'A')]}, B {groups[('remote', 'B')]}) and **{del_local} local** "
  f"(A {groups[('local_only', 'A')]}, B {groups[('local_only', 'B')]}); not deleted: "
  f"{len(not_deleted)}.")
w(f"* Remote branches now (`passo6/post_6b.json`): {', '.join(f'`{b}`' for b in post['remote_branches_now'])}. "
  f"Deleted on origin = the authorised list: {post['deleted_equals_authorised']}. Of "
  f"{post['distinct_cited_commits']} distinct commits cited in tracked files, "
  f"**{post['unreachable_from_origin']}** are unreachable from the refs on origin.")
w("")
w("### Predictions that failed, and what was learned")
w("")
w(f"* **R4 (passo 3) — live references to removed paths.** Predicted 0; the first measurement gave "
  f"{r4_first['live_references']} with a scanner that only recognised the full path; with the scanner "
  f"implementing the declared definition (any suffix of 2+ components): **{r4_corr['live_references']}** "
  f"in {r4_corr['files_with_references']} files. Corrected by `51596c0`; R4 recorded as FAIL. *Learned:* "
  f"a scanner whose result is a predicted zero must first be shown to find a known positive.")
w(f"* **D1 \"before\" inside `cyclophaser/` (passo 4).** Predicted 0; measured "
  f"**{d1_before['divergences_in_cyclophaser']}** (`passo4/before.json`): a docstring stated a stale "
  f"default for `decay_tail_amplitude_fraction`. The gate was widened by Danilo to admit docstring/comment-only "
  f"commits, each checked by a docstring-free syntax tree and the digest. *Learned:* item 31 changed defaults "
  f"without sweeping the texts that state them.")
w(f"* **P4 (passo 1).** Above: predicted {p4_pred} refusals under `\"reflect\"`, measured "
  f"{hyg['refusals']['default']}/{n}. *Learned:* the refusal depends on the incipient signal, which the "
  f"premise did not name.")
w(f"* **E1 (passo 5).** Predicted 0 failures; {e1_failed} failed in `tests/test_evaluate_batch_train.py` (a "
  f"stub of `score_labels` without the field the evaluator's new section reads). After `9bc670b`: "
  f"{e1_second[0]} passed / {e1_second[1]} failed. *Learned:* a test stub of a function's output must be "
  f"updated with the consumer.")
w(f"* **E2 (passo 5).** Predicted {e2_pred[0]} environment / {e2_pred[1]} code for the Benchmark failures "
  f"under the pinned versions; obtained **{e2_got[0]} environment / {e2_got[1]} code** — the AppTest harness "
  f"of the pinned streamlit re-applies `format_func`; the app itself was right. *Learned:* the cause was "
  f"inferred from reading code without running it.")
w(f"* **E4 (passo 5).** Predicted 0 absolute paths outside the exception; {e4b['occurrences']} before → "
  f"{e4a['occurrences']} after, all in `docs/future_work.md`, mentions of the pattern in a historical "
  f"record. *Learned:* the exception did not cover historical records.")
w(f"* **The test-id scanner (passo 5 → commit 21).** The passo-5 scanner counted only quoted 8-digit "
  f"literals in `.py` files ({tid_a['test_id_literals']} after, none in `tools/calibration_app/`); widened to "
  f"any word-bounded occurrence, it found {where_count(c21b['where'], 'tools/calibration_app/')} in "
  f"`tools/calibration_app/` text (→ {where_count(c21a['where'], 'tools/calibration_app/')} after "
  f"`dbaacd6`). *Learned:* same as R4 — the scanner was narrower than the question.")
w(f"* **0 test ids in `docs/` (commit 21).** Predicted 0 without excluding the records; measured "
  f"{where_count(c21b['where'], 'docs/')} lines before and {where_count(c21a['where'], 'docs/')} after — {where_count(c21a['where'], 'docs/future_work.md')} "
  f"in `docs/future_work.md`, {where_count(c21a['where'], 'docs/findings.md')} in a table of "
  f"`docs/findings.md`. Left for Danilo's decision. *Learned:* a prediction over a folder must say whether "
  f"historical records are in scope.")
w("")
# --- final gate (research/cleanup/final/, RELATORIO_FINAL.md) ---
fin = CLEAN / "final"
ga = json.loads((fin / "gate_a.json").read_text())
bs = json.loads((fin / "b_summary.json").read_text())
b2 = json.loads((fin / "b2_summary.json").read_text())
b2_dig = re.search(r"SHA256\s*=\s*([0-9a-f]{8})", (fin / "b2_digest_raw.txt").read_text()).group(1)
b_dig = re.search(r"SHA256\s*=\s*([0-9a-f]{8})", (fin / "b_digest_raw.txt").read_text()).group(1)
coll = re.search(r"ERROR collecting (\S+)", (fin / "b_suite_raw.txt").read_text()).group(1)
fc = json.loads((fin / "c_tag_and_trace.json").read_text())
fv = json.loads((fin / "c_verify_citations.json").read_text())
fd = json.loads((fin / "d_defaults.json").read_text())
fe = json.loads((fin / "e_d2.json").read_text())
ff = json.loads((fin / "f_post_6b.json").read_text())
verdicts = re.findall(r"^\| \((\w)\) \| \*\*(PASS|FAIL)\*\*", (CLEAN / "RELATORIO_FINAL.md").read_text(), re.M)
measured_at = re.search(r"worktree HEAD: ([0-9a-f]{7})", (fin / "gate_header.txt").read_text()).group(1)
b2_at = re.search(r"worktree HEAD: ([0-9a-f]{7})", (fin / "b2_header.txt").read_text()).group(1)
bci = {k: json.loads((fin / f"bci_{k}_summary.json").read_text()) for k in ("before", "after")}
bci_at = {k: re.search(r"worktree HEAD: ([0-9a-f]{7})", (fin / f"bci_{k}_header.txt").read_text()).group(1) for k in bci}
bci_dig = {k: re.search(r"SHA256\s*=\s*([0-9a-f]{8})", (fin / f"bci_{k}_digest_raw.txt").read_text()).group(1) for k in bci}
bci_mods = bci["before"]["ci"]["failed_by_module"]
assert list(bci_mods) == ["tests.test_app_passo5_fixes"], bci_mods
sg_b, sg_a = (json.loads((fin / f"streamlit_guards_{k}.json").read_text()) for k in ("before", "after"))
cci = (ROOT / ".circleci/config.yml").read_text()
pub_branch = re.search(r"- pypi_publish:.*?only:\s*\n\s*- (\S+)", cci, re.S).group(1)
test_pub_branch = re.search(r"- test_pypi_publish:.*?only:\s*\n\s*- (\S+)", cci, re.S).group(1)

w(f"* **The final gate's (b) — suite with 0 failures.** Measured once at `{measured_at}`: the suite stopped at "
  f"collection on `{coll}` (commit 21), a research script named `test_*.py` that pytest collects from the "
  f"root and that runs with pytest's argv; 0 tests ran. The passo-5 scanner `passo5/test_ids_in_code.py` had "
  f"been collected the same way, silently, in passo 5's suite runs, and wrote `passo5/-m.json`. *Learned:* "
  f"without a pytest `testpaths`, a research script must never be named `test_*.py`; the suites of passo 5 "
  f"ran an extra module nobody declared.")
w(f"* **The final gate's (b), in the CI environment.** (b) had been measured only in the conda environment, "
  f"which has streamlit. The CircleCI job installs the wheel with only pytest and pyyaml; reproduced in a new "
  f"venv at `{bci_at['before']}`: {bci['before']['ci']['passed']} passed / **{bci['before']['ci']['failed']} "
  f"failed**, all in `tests/test_app_passo5_fixes.py` (added by `bea55a6`, passo 5), `ModuleNotFoundError: "
  f"streamlit` — the CI has failed since passo 5. *Learned:* the criterion \"suite with 0 failures\" includes "
  f"the CI sequence, not only the development environment.")
w("")
w("### Final gate (`research/cleanup/RELATORIO_FINAL.md`)")
w("")
w(f"Measured once, in a clean worktree at `{measured_at}`, except (b): redefined by Danilo on 2026-10-02 to "
  f"include the CI sequence and measured before and after a correction. Verdicts: "
  + ", ".join(f"({k}) {v}" for k, v in verdicts) + ".")
w("")
w(f"* (a) `cyclophaser/` touched by {', '.join(f'`{c}`' for c in ga['commits_listed'])}: C1 and "
  f"{len(ga['commits_listed']) - 1} docstring/comment commits, each with an identical docstring-free tree and "
  f"equal digests; HEAD's docstring-free tree is identical to `742e685`'s: {ga['head_vs_c1']['identical']}.")
w(f"* (b) First measurement FAIL, as above. App tests in a fresh venv with `requirements-app.txt`: {bs['app_pinned']['passed']} "
  f"passed / {bs['app_pinned']['failed']} failed; digest `{b_dig}…`. The two scanners were renamed to "
  f"`scan_*` and `passo5/-m.json` removed (`d44802e`); a **second measurement** at `{b2_at}`, recorded beside "
  f"the first, which stands: suite {b2['suite']['passed']} passed / {b2['suite']['failed']} failed, app tests "
  f"in the same run {b2['app_dedicated']['passed']} passed / {b2['app_dedicated']['failed']} failed, digest "
  f"`{b2_dig}…`.")
w(f"* (b) with the CI sequence (`research/cleanup/final/run_b_ci.sh`; predictions `final/PREVISOES_ci.md`, "
  f"committed before measuring). Correction `0b21e51`: the `_app()` helper of `tests/test_app_passo5_fixes.py` "
  f"calls `pytest.importorskip(\"streamlit\")`, so only the tests that drive the app skip without streamlit "
  f"(unguarded streamlit imports in the test files: {sg_b['unguarded_imports']} before, "
  f"{sg_a['unguarded_imports']} after, `final/scan_streamlit_guards.py`). CI sequence before → after: "
  f"{bci['before']['ci']['passed']} / {bci['before']['ci']['failed']} / {bci['before']['ci']['skipped']} → "
  f"**{bci['after']['ci']['passed']} / {bci['after']['ci']['failed']} / {bci['after']['ci']['skipped']}** "
  f"(passed / failed / skipped); conda `-m \"not browser\"` after: {bci['after']['conda']['passed']} passed / "
  f"{bci['after']['conda']['failed']} failed; digest `{bci_dig['before']}…` → `{bci_dig['after']}…`. The same "
  f"commit removes `runtime.txt` and `.python-version`, which no tracked file reads.")
w(f"* (c) §S10 {fc['R3']['rows']} rows, {len(fc['R3']['failures'])} failures; `verify_citations` "
  f"{fv['citations_resolved']}/{fv['citations_total']}, {len(fv['failures'])} failures.")
w(f"* (d) {fd['divergences']} divergences in {fd['claims']} default claims.")
w(f"* (e) {fe['flagged']} flagged lines, {fe['carried']} with file, text and context identical to the Fase C "
  f"review; {fe['attributing']} attribute an `edge` score to the current default.")
w(f"* (f) remote branches deleted = the authorised list: {ff['deleted_equals_authorised']}.")
w("")
w("### Pending — for the release front")
w("")
w("* **Order:** publish 2.1 on PyPI → raise the app's requirement to `cyclophaser>=2.1` → merge into "
  "`master` → restart the published app. "
  f"Today the app requires {', '.join(f'`{r}`' for r in rtd['app_requirements_cyclophaser'])} "
  "(`tools/calibration_app/requirements.txt`), and the latest PyPI release predates the parameters the app "
  "reads (§S11).")
w(f"* **(i) `pypi_publish` publishes to PyPI on every push to `{pub_branch}`** (`.circleci/config.yml`), so "
  f"the version in `setup.py` must change BEFORE the merge into `{pub_branch}`, and the app, which deploys "
  f"from `{pub_branch}`, must be restarted after the CI has published 2.1.")
w("* **(ii) Check that the app runs Python 3.12** in its settings on Streamlit Community Cloud "
  "(`runtime.txt` and `.python-version` were removed; that platform does not read them).")
w(f"* **(iii) `test_pypi_publish` runs only on the branch `{test_pub_branch}`**, which is still to be created.")
w(f"* **Version strings:** `setup.py` and `docs/conf.py` still say `{rtd['setup_version']}` / "
  f"`{rtd['conf_release']}`.")
w("* **Create the permanent `develop` branch**: the contributing page sends pull requests to `develop`, "
  "which does not exist.")
w(f"* **Read the Docs keeps building `{rtd['default_branch']}`** (the default branch), so the rewritten site "
  f"is published only after the merge into `{rtd['default_branch']}`.")
w(f"* **CI** tests only Python {ci} (`passo4/ci_python.md`), and may be importing the checked-out tree rather "
  f"than the installed wheel (`python -m pytest` from the checkout root; read from the configuration, not "
  f"measured).")
w("* The other open items stay in §S11 of `docs/findings.md`.")
w("")
w("---")
w("")

text = "\n".join(T)
assert not re.search(r"\{|\}", text.replace("`{", "").replace("}`", "")), "unformatted placeholder"
(HERE / "future_work_item32.md").write_text(text)
print(text)

if sys.argv[1:] == ["--replace"]:
    fw = ROOT / "docs/future_work.md"
    src = fw.read_text()
    a = re.search(r"^## 32\.", src, re.M).start()
    b = src.index("\n## Note\n") + 1
    assert re.findall(r"^## (\d+)[a-z]?\.", src[a:b], re.M) == ["32"], "replace must touch item 32 only"
    fw.write_text(src[:a] + text + "\n" + src[b:])
    print(f"replaced item 32 in {fw.relative_to(ROOT)}")

if sys.argv[1:] == ["--insert"]:
    fw = ROOT / "docs/future_work.md"
    src = fw.read_text()
    assert not re.search(r"^## 32\.", src, re.M), "item 32 already exists"
    last = [int(m.group(1)) for m in re.finditer(r"^## (\d+)[a-z]?\.", src, re.M)]
    assert max(last) == 31, max(last)
    anchor = "\n## Note\n"
    assert src.count(anchor) == 1
    i = src.index(anchor) + 1
    fw.write_text(src[:i] + text + "\n" + src[i:])
    print(f"inserted into {fw.relative_to(ROOT)}")
