#!/usr/bin/env python
"""Tables of the "Defaults and what was calibrated" page (docs/defaults.rst).

    python docs/figures/make_doc_tables.py

Nothing in them is typed. Writes, under docs/generated/:

  defaults_filtering.csv      the defaults of process_vorticity (signature), and
                              the same parameter's default in determine_periods
  defaults_phases.csv         the defaults of get_periods (signature), and in
                              determine_periods
  params_track_vs_defaults.csv  every key of the params-track preset
                              (research/labels/configs/cyclophaser_params-track.yaml)
                              against the package default; "same" or "differs"
  boundary_padding_effect.inc the measured effect of the boundary_padding default,
                              read from research/cleanup/passo1/hygiene_train.json
                              (training series, no scoring against labels)

Run from a clone of the repository (the last two read repository files).
"""
import csv
import importlib
import inspect
import json
import sys
from pathlib import Path

import yaml

importlib.import_module("cyclophaser.determine_periods")
DP = sys.modules["cyclophaser.determine_periods"]

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "generated"
PRESET = ROOT / "research/labels/configs/cyclophaser_params-track.yaml"
HYGIENE = ROOT / "research/cleanup/passo1/hygiene_train.json"


def defaults(fn):
    return {k: v.default for k, v in inspect.signature(fn).parameters.items()
            if v.default is not inspect.Parameter.empty}


def show(v):
    return "None" if v is None else repr(v)


def table(path, fn, skip=()):
    own, top = defaults(fn), defaults(DP.determine_periods)
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["parameter", "default", "default in determine_periods"])
        for k, v in own.items():
            if k in skip:
                continue
            w.writerow([f"``{k}``", f"``{show(v)}``", f"``{show(top[k])}``" if k in top else "(not a parameter)"])


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    table(OUT / "defaults_filtering.csv", DP.process_vorticity)
    table(OUT / "defaults_phases.csv", DP.get_periods, skip=("plot", "plot_steps", "export_dict"))

    cfg = yaml.safe_load(PRESET.read_text())
    top = defaults(DP.determine_periods)
    with open(OUT / "params_track_vs_defaults.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["section", "parameter", "params-track", "package default", ""])
        for section in ("filter_params", "phase_params"):
            for k, v in cfg[section].items():
                d = top.get(k, "(not a parameter)")
                w.writerow([section, f"``{k}``", f"``{show(v)}``", f"``{show(d)}``",
                            "same" if v == d else "**differs**"])

    h = json.loads(HYGIENE.read_text())["summary"]
    rel = HYGIENE.relative_to(ROOT)
    (OUT / "boundary_padding_effect.inc").write_text(
        f"On the {h['n_train']} training series, running the package defaults (``boundary_padding=\"reflect\"``) "
        f"and the same defaults with ``boundary_padding=\"edge\"``, without scoring either against the manual "
        f"labels:\n\n"
        f"* the final phases differ on {h['maps_changed']} of {h['n_train']} series, and the phase sequence on "
        f"{h['sequences_changed']};\n"
        f"* the number of series that get no incipient phase is the same: {h['refusals']['default']} of "
        f"{h['n_train']} under ``\"reflect\"`` and {h['refusals']['edge']} of {h['n_train']} under ``\"edge\"``;\n"
        f"* no run raised an exception ({h['exceptions']['default']} and {h['exceptions']['edge']}), and "
        f"no phase sequence was invalid ({h['invalid_sequences']['default']} and "
        f"{h['invalid_sequences']['edge']}).\n\n"
        f"Source: ``{rel}`` in the repository (generated by "
        f"``{rel.with_name('hygiene_train.py').as_posix()}``).\n")
    print("written:", ", ".join(p.name for p in (OUT / "defaults_filtering.csv", OUT / "defaults_phases.csv",
                                                 OUT / "params_track_vs_defaults.csv",
                                                 OUT / "boundary_padding_effect.inc")))


if __name__ == "__main__":
    main()
