#!/usr/bin/env python
"""Final gate (e) — D2 redone on the tree it runs in (no live text attributes to the
current default scores measured under boundary_padding="edge").

    python research/cleanup/final/d2_head.py LABEL [--list]   # writes LABEL.json / LABEL.md next to it

Steps 1 and 2 (which lines talk about a score, and which of those have edge,
params-track, params-15 or the default(s) in context) are passo4/d2_edge_scores.py's
own, imported. Step 3 (review):
* a flagged line whose file, text AND five-line context are identical to a line
  flagged by the Fase C run at REF (ff4eb3b, passo4/faseC_d2.json) keeps that
  line's verdict — the reviewed thing did not change;
* every other flagged line has its verdict in REVIEW_HEAD below, written after
  reading it in context on this branch;
* a flagged line with no verdict fails.
--list prints the flagged lines and whether each is carried, without verdicts
for the others (used to write REVIEW_HEAD before the gate run).
"""
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
REF = "ff4eb3b"
spec = importlib.util.spec_from_file_location("d2", HERE.parent / "passo4/d2_edge_scores.py")
d2 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(d2)

REVIEW_HEAD = {}  # "file:line" -> verdict


def at(ref, path):
    p = subprocess.run(["git", "show", f"{ref}:{path}"], cwd=ROOT, capture_output=True, text=True)
    return p.stdout.splitlines() if p.returncode == 0 else None


def ctx(lines, i):
    return lines[max(0, i - 3):i + 2]


old = json.loads(subprocess.check_output(["git", "show", f"{REF}:research/cleanup/passo4/faseC_d2.json"],
                                         cwd=ROOT, text=True))
old_files = {}
carried = {}
for r in old["flagged_rows"]:
    f, n = r["where"].rsplit(":", 1)
    if f not in old_files:
        old_files[f] = at(REF, f)
    carried[(f, tuple(ctx(old_files[f], int(n))))] = (r["where"], r["verdict"])


def flagged_rows():
    rows = []
    sources = [(f.relative_to(ROOT).as_posix(), f.read_text().splitlines(), None) for f in d2.live_files()]
    cl, cl_all = d2.changelog_unreleased()
    sources.append(("CHANGELOG.md", cl_all, {n for n, _ in cl}))
    n_score = 0
    for name, lines, only in sources:
        for i, line in enumerate(lines, 1):
            if (only is not None and i not in only) or not d2.SCORE.search(line):
                continue
            n_score += 1
            if not d2.CTX.search(" ".join(ctx(lines, i))):
                continue
            row = dict(where=f"{name}:{i}", text=line.strip()[:200])
            c = carried.get((name, tuple(ctx(lines, i))))
            if c:
                row.update(verdict=c[1], source=f"carried from {c[0]}@{REF} (file, text and context identical)")
            elif row["where"] in REVIEW_HEAD:
                row.update(verdict=REVIEW_HEAD[row["where"]], source="reviewed on this branch")
            rows.append(row)
    return n_score, rows


label = sys.argv[1]
n_score, rows = flagged_rows()
if "--list" in sys.argv:
    for r in rows:
        print(("CARRIED " if "source" in r and r["source"].startswith("carried") else "REVIEW  ") + r["where"], "|", r["text"][:140])
    print(f"score lines {n_score}; flagged {len(rows)}; carried {sum('carried' in r.get('source', '') for r in rows)}")
    sys.exit(0)
missing = [r for r in rows if not r.get("verdict")]
attributing = [r for r in rows if (r.get("verdict") or "").startswith("ATTRIBUTES")]
out = dict(label=label, ref_for_carried_verdicts=REF, score_lines=n_score, flagged=len(rows),
           carried=sum("carried" in r.get("source", "") for r in rows),
           reviewed_on_branch=sum(r.get("source") == "reviewed on this branch" for r in rows),
           unreviewed=len(missing), attributing=len(attributing), flagged_rows=rows)
(HERE / f"{label}.json").write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n")
md = [f"# {label} — D2 on this tree (generated by final/d2_head.py)\n",
      f"Score lines {n_score}; flagged {len(rows)} (carried from `{REF}` {out['carried']}, reviewed on this branch "
      f"{out['reviewed_on_branch']}); without a verdict {len(missing)}; attributing an edge-measured score to the "
      f"current default: **{len(attributing)}**.\n", "| where | text | verdict | source |", "|---|---|---|---|"]
md += [f"| `{r['where']}` | {r['text'].replace('|', chr(92) + '|')} | {r.get('verdict') or '**(none)**'} | "
       f"{r.get('source', '')} |" for r in rows]
(HERE / f"{label}.md").write_text("\n".join(md) + "\n")
print(md[1])
sys.exit(1 if missing or attributing else 0)
