#!/usr/bin/env python
"""Front B - the default-behaviour SHA256, the integrity reference for part 2.

    python research/labels/diagnostics/front_b/default_behaviour_hash.py

WHAT IS HASHED - exact definition
---------------------------------
1. SERIES. The 47 ids listed under `train:` in `research/labels/split.yaml`
   (35 real + 12 synthetic), sorted ascending as Python strings. Real series are
   read by `labels_core.load_real_series()` from `tests/calibration_data/*.csv`
   (column `min_max_zeta_850`, `;` separator, pandas' DEFAULT float parser -
   see that function's docstring for why not round_trip). Synthetic series are
   read by `labels_core.load_synthetic_series()` from the FROZEN CSVs in
   `tests/synthetic/data/`, never regenerated from `cases.py`.
   The 16 TEST ids are not read at all.

2. CONFIG. `get_periods(process_vorticity(df))` with NO arguments beyond the
   frame - i.e. cyclophaser PACKAGE DEFAULTS, not `cyclophaser_params-9.yaml`.
   Defaults are used deliberately: the hash must detect an unintended change to
   the shipped behaviour, so it must not be pinned to one calibration export.

3. FORMAT. For each id, in sorted order, one line:

       "<id>:<p0>|<p1>|...|<pN-1>"

   where each `p` is `str()` of that timestep's entry in the returned `periods`
   column (phase names carry the detector's own numbering, e.g.
   "intensification 2"). Lines are joined with "\n" - no trailing newline.

4. HASH. `hashlib.sha256(blob.encode()).hexdigest()` over the UTF-8 bytes.

`series_sha256` from `labels_core` is verified for every series before hashing,
so a drifted input fails loudly instead of silently changing the digest.
"""
from __future__ import annotations

import hashlib
import sys
import warnings
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO / "research" / "labels"))
sys.path.insert(0, str(REPO))

from labels_core import (load_real_series, load_synthetic_series, read_labels,
                         read_split, series_sha256)
from cyclophaser.determine_periods import get_periods, process_vorticity

OUT = Path(__file__).resolve().parent


def main():
    import cyclophaser
    print(f"cyclophaser.__file__ = {cyclophaser.__file__}")
    if not str(Path(cyclophaser.__file__).resolve()).startswith(str(REPO.resolve())):
        sys.exit("REFUSING: cyclophaser does not resolve to this working tree.")

    split = read_split()
    train = set(split["train"])
    real = {k: v for k, v in load_real_series().items() if k in train}
    syn = {k: v for k, v in load_synthetic_series()[0].items() if k in train}
    series = {**real, **syn}
    assert len(series) == len(train), f"{len(series)} != {len(train)}"

    labels = read_labels()
    stale = [sid for sid, v in series.items()
             if sid in labels and series_sha256(v) != labels[sid]["series_sha256"]]
    if stale:
        sys.exit(f"REFUSING: series_sha256 mismatch on {stale}")
    print(f"series_sha256 verified for all {len(series)} training series.")

    recs = []
    for sid in sorted(series):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = get_periods(process_vorticity(pd.DataFrame({"zeta": series[sid]})))
        recs.append(sid + ":" + "|".join(res["periods"].astype(str)))

    blob = "\n".join(recs)
    digest = hashlib.sha256(blob.encode()).hexdigest()
    print(f"n_series = {len(recs)}")
    print(f"SHA256   = {digest}")

    (OUT / "default_behaviour_sha256.txt").write_text(
        "Front B - default-behaviour SHA256 (integrity reference for part 2)\n"
        "Generated by: research/labels/diagnostics/front_b/default_behaviour_hash.py\n"
        "See that script's module docstring for the exact definition.\n\n"
        "series  : 47 TRAIN ids from research/labels/split.yaml, sorted ascending\n"
        "          (35 real from tests/calibration_data, 12 synthetic from the\n"
        "          frozen tests/synthetic/data CSVs). TEST split not read.\n"
        "config  : cyclophaser PACKAGE DEFAULTS - get_periods(process_vorticity(df))\n"
        "          with no further arguments. NOT cyclophaser_params-9.yaml.\n"
        "format  : one line per id, '<id>:<periods joined by |>', lines joined\n"
        "          with newline, no trailing newline; sha256 of the UTF-8 bytes.\n\n"
        f"n_series: {len(recs)}\n"
        f"sha256  : {digest}\n")
    print(f"\nwrote {OUT / 'default_behaviour_sha256.txt'}")


if __name__ == "__main__":
    main()
