"""Passo 0 — the JUDGEMENT half of the manifest (hand-written, read by make_manifest.py).

Everything mechanical (paths, types, last commits, references, grep hits,
counts) is generated by inventory.py / branches.py / defaults_in_text.py.
This file holds only what needs judgement: destination, reason, the one-line
finding and where it is already recorded.

Rules this file follows:
  * No number is typed here. A finding is described qualitatively; the number
    lives where the anchor points.
  * An anchor is (file, needle). make_manifest.py resolves it to file:line and
    FAILS if the needle is absent or matches more than one line — a moved or
    ambiguous anchor cannot slip through as a stale line number.
  * Every tracked file must be covered by a rule below, and every generated
    output under research/ needs a finding; make_manifest.py fails otherwise.
"""

FW = "docs/future_work.md"
DIAG = "research/labels/diagnostics/"

# --------------------------------------------------------------------------- #
# Consolidated findings document (Passo 2): proposed sections.
SECTIONS = {
    "S01": "Filtro de Lanczos e padding de borda (itens 3c, 4, 8(d))",
    "S02": "Fase incipiente: método plateau, suavização, recusa (relatórios incipient_plateau, itens 25, 26)",
    "S03": "Índice 0: tipo do extremo e reclassificação (Front A, itens 8, 27, 28)",
    "S04": "Mature: proeminência × amplitude, profundidade, pareamento (itens 20, 20(a), 22)",
    "S05": "Intensification: piso de profundidade (item 24)",
    "S06": "`distance` / `length_scale` (Front B, item 19)",
    "S07": "Plateau que sobrescreve intensification; lote swell (item 30)",
    "S08": "params-15/params-track como default do pacote; exposição do teste (item 31)",
    "S09": "Parâmetros inertes no app (item 9(b))",
    "S10": "Rastreabilidade: scripts aposentados, instrumentos, índices de recuperação",
}

# --------------------------------------------------------------------------- #
# Per front directory: register anchor in future_work.md and consolidation section.
FRONTS = {
    DIAG + "front_b/":         dict(fw="## 19. Front B", sec="S06"),
    DIAG + "frontA_reverify/": dict(fw="## 27. Front A′", sec="S03"),
    DIAG + "frontA_idx0_c2/":  dict(fw="## 28. Front A —", sec="S03"),
    DIAG + "frontC/":          dict(fw="## 24. Front C", sec="S05"),
    DIAG + "frontD/":          dict(fw="## 25. Front D", sec="S02"),
    DIAG + "frontRefusal/":    dict(fw="## 26. Front \"incipient refusal\"", sec="S02"),
    DIAG + "item19/":          dict(fw="## 20. Mature detection", sec="S04"),
    DIAG + "item20a/":         dict(fw="### 20(a) — `mature_amplitude_fraction`", sec="S04"),
    DIAG + "item20b/":         dict(fw="## 22. Front 20(b)", sec="S04"),
    DIAG + "item30/":          dict(fw="## 30. Plateau overwriting", sec="S07"),
    DIAG + "item31/":          dict(fw="## 31. params-15 as the package default", sec="S08"),
    "research/incipient_plateau/": dict(fw="## 15. Synthetic incipient ground truth", sec="S02"),
    "research/inert_params/":  dict(fw="### (b) F(iii)", sec="S09"),
}

# --------------------------------------------------------------------------- #
# KEEP overrides (destination "manter") with the reason. Checked before rules.
KEEP = {
    # canonical instruments / live dependencies inside diagnostics/
    DIAG + "front_b/default_behaviour_hash.py":
        "gerador canônico do digest default (linha de base de toda frente)",
    DIAG + "front_b/default_behaviour_sha256.txt":
        "livro-razão do gerador canônico (o script anexa registros a ele)",
    DIAG + "frontA_reverify/run_in_worktree.py":
        "modelo de execução em worktree com assert de cyclophaser.__file__ (regra fixa)",
    DIAG + "item19/item19_core.py":
        "importado pelo app (benchmark_core: pair_by_overlap, MARGIN) — medidor vivo",
    DIAG + "item30/item30_core.py":
        "importado por teste vivo (tests/test_item30_spare_intensification.py)",
    DIAG + "item30/figs_cf.py":
        "importado por teste vivo (tests/test_item30_spare_intensification.py)",
    DIAG + "item30/separability.py":
        "importado por teste vivo via figs_cf (sep.candidates)",
    DIAG + "item31/param_table.json":
        "lido por teste vivo (tests/test_config_defaults.py, PARAM_TABLE)",
    DIAG + "item31/param_table.py":
        "gerador do param_table.json lido por teste vivo",
    DIAG + "item31/recovery_table.md":
        "índice de recuperação de params-1..14 (citado pelo app README e por teste vivo)",
    DIAG + "item31/recovery_table.json":
        "dados do índice de recuperação (mesmo gerador)",
    DIAG + "item31/recovery_table.py":
        "gerador do índice de recuperação",
    "research/app_layer_inspector/gen_inspector_figures.py":
        "citado pelo app (inspector_mpl.py, README do app) como gerador das figuras",
    "research/labels/front_g/front_g_synthetic_deviations.md":
        "citado por teste vivo (test_synthetic_lifecycles.py); tabela por fronteira",
    "research/labels/front_g/front_g_deviation_table.py":
        "gerador da tabela citada por teste vivo",
    "research/incipient_plateau/measure_incipient_smoothing.py":
        "citado por comentário vivo do pacote (o alvo do comentário tem de existir; linha em 'registrado em')",
}

# Anchors shown in the "registrado em" column of a KEPT file: who cites it.
KEEP_ANCHORS = {
    "research/incipient_plateau/measure_incipient_smoothing.py":
        [("cyclophaser/find_stages.py", "research/incipient_plateau/measure_incipient_smoothing.py")],
}

# Destination overrides that are NOT "manter" (dest, reason).
DEST = {
    ".pypirc": ("remover",
                "arquivo de credenciais do PyPI versionado; NÃO LIDO neste inventário — "
                "Danilo verifica o conteúdo e, se houver token, revoga-o antes"),
    "Pipfile": ("remover",
                "pins de 2024 que não batem com setup.py/environment.yml; nenhum "
                "CI/RTD/env o usa (environment.yml é o canônico)"),
    "docs/_images/density_map_Aggregate.png": ("remover",
                "órfã: nenhum arquivo a referencia (última mudança na 1.8.7)"),
    "tests/calibration_data/gen_real_before_after.py": ("remover",
                "gerador exploratório de figuras (frente de proeminência); não é teste nem dado; figuras não "
                "versionadas; só citado por scripts que também saem"),
    "tests/synthetic/gen_extrema_before_after.py": ("remover",
                "gerador exploratório de figuras (frente de proeminência); não é teste; figuras não versionadas; "
                "só citado por um script que também sai"),
    DIAG + "item31/stale_scripts.md": ("consolidar",
                "índice dos scripts que param de rodar; vira seção de rastreabilidade"),
    DIAG + "item31/exposure_table.md": ("consolidar",
                "registro de exposição das séries de TESTE — precisa sobreviver à limpeza"),
    DIAG + "item31/test_label_census.txt": ("consolidar",
                "censo declarado dos rótulos de TESTE (contagens) — registro de exposição"),
}

# --------------------------------------------------------------------------- #
# Findings. path -> (finding, [anchors]). Anchors: (file, needle), resolved to
# file:line. A glob key (containing "*") covers a homogeneous group.
R = {k: k + "REPORT.md" for k in FRONTS}
FB = DIAG + "front_b/"
FAR = DIAG + "frontA_reverify/"
FAC = DIAG + "frontA_idx0_c2/"
FC = DIAG + "frontC/"
FD = DIAG + "frontD/"
FR = DIAG + "frontRefusal/"
I19 = DIAG + "item19/"
I20A = DIAG + "item20a/"
I20B = DIAG + "item20b/"
I30 = DIAG + "item30/"
I31 = DIAG + "item31/"
IP = "research/incipient_plateau/"
IN = "research/inert_params/"

FINDING = {
    # ---------------- front_b ----------------
    FB + "distance_sweep.txt": ("varredura de `distance` nas séries de treino: parâmetro inerte na referência",
                                [(FB + "ADDENDUM_part1b.md", "## 1. The `distance` sweep"), (FW, "## 19. Front B")]),
    FB + "headroom_and_hash.txt": ("folga de `distance` e primeiro registro do digest default",
                                   [(FB + "REPORT_front_b_part1.md", "## 6. Default-behaviour SHA256")]),
    FB + "mature_pairing_audit.txt": ("o que o n do pareamento mature conta e o que foi excluído",
                                      [(FB + "ADDENDUM_part1b.md", "## 2. What `n=45` counts")]),
    FB + "reference_score_attribution.txt": ("proveniência de cada número de referência (armadilha de atribuição)",
                                             [(FB + "ADDENDUM_part1b.md", "## 4. Provenance of every reference number")]),
    FB + "sensitivity.txt": ("sonda causal: sensibilidade das fases a `distance`/`length_scale`",
                             [(FB + "REPORT_front_b_part1.md", "### Why `distance` is inert, quantified")]),
    FB + "target_tracks.txt": ("as duas trajetórias-alvo: janelas mature e extremos antes/depois do filtro",
                               [(FB + "REPORT_front_b_part1.md", "## 3. The two target tracks")]),
    FB + "topology_run_gate_excerpt.txt": ("trecho do gate de topologia citado como referência (score de pacote)",
                                           [(FB + "ADDENDUM_part1b.md", "## 4. Provenance of every reference number")]),
    FB + "train_aggregate.txt": ("agregado do split de treino sob a config de referência da época",
                                 [(FB + "REPORT_front_b_part1.md", "## 4. Train split, 35 real + 12 synthetic")]),
    FB + "train_raw.json": ("dados brutos por série do diagnóstico de treino",
                            [(FB + "REPORT_front_b_part1.md", "## 4. Train split, 35 real + 12 synthetic")]),
    FB + "sweep_distance.py": ("docstring registra a menor folga sobrevivente e em que série",
                               [(FB + "ADDENDUM_part1b.md", "gap analysis is confirmed exactly")]),

    # ---------------- frontA_reverify ----------------
    FAR + "outputs/1a_gate.log": ("gate 1a: reprodução campo a campo dos artefatos de A — PASS",
                                  [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)"), (FW, "### Step 1a — gate — **PASS**")]),
    FAR + "outputs/1a_build_final_output_check.log": ("log (proveniência + corpo) da regeneração do final_output_check no passo 1a",
                                                      [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/1a_build_idx0_inventory.log": ("log da regeneração do inventário idx0 no passo 1a",
                                                  [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/1a_capture_pipeline_state.log": ("log da captura do estado do pipeline no passo 1a",
                                                    [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/1a_eval_raw.log": ("saída do avaliador no passo 1a (reprodução de A)",
                                      [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/step1a_regen_final_output_check.csv": ("tabela regenerada final_output_check (passo 1a)",
                                                          [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/step1a_regen_fix_eval_before.txt": ("avaliação regenerada 'antes do fix' de A (passo 1a)",
                                                       [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/step1a_regen_idx0_final_stage.csv": ("tabela regenerada idx0_final_stage (passo 1a)",
                                                        [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/step1a_regen_idx0_inventory.csv": ("tabela regenerada idx0_inventory (passo 1a)",
                                                      [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/step1a_regen_idx0b_prominence.csv": ("tabela regenerada idx0b_prominence (passo 1a)",
                                                        [(FAR + "REPORT.md", "## STEP 1a — environment (GATE)")]),
    FAR + "outputs/1b_census.log": ("censo do passo 1b na ponta com params-9",
                                    [(FAR + "REPORT.md", "## STEP 1b — code drift"), (FW, "### Steps 1b and 2 — diagnostics")]),
    FAR + "outputs/1b_diff_vs_A.log": ("diff por trajetória contra A no passo 1b: nenhuma diferença",
                                       [(FAR + "REPORT.md", "### Differences against Front A: **none**"), (FW, "### Steps 1b and 2 — diagnostics")]),
    FAR + "outputs/1b_eval_params9.log": ("avaliador na ponta com params-9 (incipient, recusa) idêntico a A",
                                          [(FW, "Incipient boundary on TRAIN under params-9 at the tip")]),
    FAR + "outputs/step1b_params9_V_table.csv": ("tabela V (primeira fase não-incipient) sob params-9",
                                                 [(FAR + "REPORT.md", "## STEP 1b — code drift")]),
    FAR + "outputs/step1b_params9_idx0_final_stage.csv": ("idx0_final_stage sob params-9 (passo 1b)",
                                                          [(FAR + "REPORT.md", "## STEP 1b — code drift")]),
    FAR + "outputs/step1b_params9_idx0_inventory.csv": ("idx0_inventory sob params-9 (passo 1b)",
                                                        [(FAR + "REPORT.md", "## STEP 1b — code drift")]),
    FAR + "outputs/step1b_params9_idx0b_prominence.csv": ("idx0b_prominence sob params-9 (passo 1b)",
                                                          [(FAR + "REPORT.md", "## STEP 1b — code drift")]),
    FAR + "outputs/2_census.log": ("censo do passo 2 com params-13",
                                   [(FAR + "REPORT.md", "## STEP 2 — current state"), (FW, "### Steps 1b and 2 — diagnostics")]),
    FAR + "outputs/2_diff_vs_A.log": ("diff contra A no passo 2 (params-13): nenhuma diferença",
                                      [(FAR + "REPORT.md", "**0 differences**, same as step 1b")]),
    FAR + "outputs/2_attribution.log": ("atribuição chave-a-chave da perda de mature em 20191014 a mature_min_depth",
                                        [(FAR + "REPORT.md", "### Attribution"), (FW, "### The one behavioural difference found anywhere")]),
    FAR + "outputs/step2_attribution.csv": ("tabela da atribuição chave-a-chave (passo 2)",
                                            [(FAR + "REPORT.md", "### Attribution")]),
    FAR + "outputs/step2_params13_V_table.csv": ("tabela V sob params-13",
                                                 [(FAR + "REPORT.md", "## STEP 2 — current state")]),
    FAR + "outputs/step2_params13_idx0_final_stage.csv": ("idx0_final_stage sob params-13",
                                                          [(FAR + "REPORT.md", "## STEP 2 — current state")]),
    FAR + "outputs/step2_params13_idx0_inventory.csv": ("idx0_inventory sob params-13",
                                                        [(FAR + "REPORT.md", "## STEP 2 — current state")]),
    FAR + "outputs/step2_params13_idx0b_prominence.csv": ("idx0b_prominence sob params-13",
                                                          [(FAR + "REPORT.md", "## STEP 2 — current state")]),

    # ---------------- frontA_idx0_c2 ----------------
    FAC + "outputs/m1_m2_census.log": ("M1/M2: como a proeminência do idx0 é computada e onde C2 dispararia",
                                       [(FAC + "REPORT.md", "## M1 — how the prominence of index 0 is computed"), (FAC + "REPORT.md", "## M2 — where C2 would fire")]),
    FAC + "outputs/m2_c2_table.csv": ("tabela por série de onde C2 dispara",
                                      [(FAC + "REPORT.md", "## M2 — where C2 would fire")]),
    FAC + "outputs/m2b_peak_to_valley.csv": ("o ramo peak->valley de C2 onde dispara (20190639)",
                                             [(FAC + "REPORT.md", "### Addendum — what the `peak->valley` branch does")]),
    FAC + "outputs/m2b_peak_to_valley.log": ("log do adendo M2 (ramo peak->valley)",
                                             [(FAC + "REPORT.md", "### Addendum — what the `peak->valley` branch does")]),
    FAC + "outputs/m3_force_peak.csv": ("M3: forçar idx0 a peak sob params-13",
                                        [(FAC + "REPORT.md", "## M3 — forcing index 0 to `peak` under params-13")]),
    FAC + "outputs/m3_force_peak.log": ("log de M3",
                                        [(FAC + "REPORT.md", "## M3 — forcing index 0 to `peak` under params-13")]),
    FAC + "outputs/m3_force_peak.png": ("figura de M3",
                                        [(FAC + "REPORT.md", "## M3 — forcing index 0 to `peak` under params-13")]),
    FAC + "outputs/m4_20180608_H.csv": ("M4: a sobrescrita incipient (defeito H) mascara o efeito em 20180608",
                                        [(FAC + "REPORT.md", "## M4 — 20180608: does the incipient overwrite (H) mask the effect?")]),
    FAC + "outputs/m4_20180608_H.log": ("log de M4",
                                        [(FAC + "REPORT.md", "## M4 — 20180608: does the incipient overwrite (H) mask the effect?")]),
    FAC + "outputs/m4_20180608_H.png": ("figura de M4",
                                        [(FAC + "REPORT.md", "## M4 — 20180608: does the incipient overwrite (H) mask the effect?")]),
    FAC + "outputs/m4_20180608_head.csv": ("cabeça da série 20180608 antes/depois de H (M4)",
                                           [(FAC + "REPORT.md", "## M4 — 20180608: does the incipient overwrite (H) mask the effect?")]),
    FAC + "outputs/m5_boundary_independence.csv": ("M5: a fronteira incipient não depende do mapa de fases",
                                                   [(FAC + "REPORT.md", "## M5 — does `boundary` depend on the phase map?"), (FW, "### M5 — the incipient boundary is upstream")]),
    FAC + "outputs/m5_boundary_independence.log": ("log de M5",
                                                   [(FAC + "REPORT.md", "## M5 — does `boundary` depend on the phase map?")]),
    FAC + "outputs/fig_20190639.log": ("log da figura de 20190639 (blocos C2 vs rótulo)",
                                       [(FAC + "REPORT.md", "## Maintainer ruling — `20190639`")]),
    FAC + "outputs/fig_20190639_blocks.csv": ("blocos de 20190639: rótulo, base, C2",
                                              [(FAC + "REPORT.md", "## Maintainer ruling — `20190639`")]),
    FAC + "outputs/fig_20190639_boundaries.csv": ("erro por fronteira de 20190639: base vs C2",
                                                  [(FAC + "REPORT.md", "## Maintainer ruling — `20190639`")]),
    FAC + "outputs/fig_20190639_c2.png": ("figura de 20190639 sob C2",
                                          [(FAC + "REPORT.md", "## Maintainer ruling — `20190639`")]),
    FAC + "outputs/fp_ref_c714451.json": ("impressão digital de referência (c714451) para o gate da etapa 2",
                                          [(FAC + "REPORT.md", "## The gate"), (FW, "| Q1 | `False` == c714451, 63/63 | 63/63 | CONFIRMED |")]),
    FAC + "outputs/fp_ref_c714451.log": ("log da impressão digital de referência",
                                         [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/fp_cur_off.json": ("impressão digital do tree com a flag desligada",
                                      [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/fp_cur_off.log": ("log da impressão digital (flag off)",
                                     [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/fp_cur_on.json": ("impressão digital do tree com a flag ligada",
                                     [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/fp_cur_on.log": ("log da impressão digital (flag on)",
                                    [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/stage2_gate.log": ("gate da etapa 2 (Q1–Q8) — PASS",
                                      [(FAC + "REPORT.md", "## The gate"), (FW, "### Stage 2 — rule C2' as default behaviour")]),
    FAC + "outputs/stage2_table.csv": ("tabela por série da etapa 2 (dispara, ramo, sequências off/on)",
                                       [(FAC + "REPORT.md", "## Sequence-match count, and the exception")]),
    FAC + "outputs/stage2_changed_series.png": ("figura das séries alteradas pela regra C2'",
                                                [(FAC + "REPORT.md", "## The gate")]),
    FAC + "outputs/stage2_defaults_check.csv": ("sob os defaults do pacote a nova regra não muda nada",
                                                [(FW, "#### The finding that matters most")]),
    FAC + "outputs/stage2_defaults_check.log": ("log da checagem sob defaults do pacote",
                                                [(FW, "#### The finding that matters most")]),

    # ---------------- frontC ----------------
    FC + "d2_segments.csv": ("segmentos de intensificação e sua profundidade D2 (separação no treino)",
                             [(FC + "REPORT.md", "## Measured — TRAIN split"), (FW, "### Separation measured on TRAIN")]),
    FC + "d2_segments.json": ("mesmos segmentos D2, formato bruto",
                              [(FW, "### Separation measured on TRAIN")]),
    FC + "fig_20180654_before_after.png": ("antes/depois do piso de intensificação em 20180654",
                                           [(FC + "REPORT.md", "## Measured — TRAIN split")]),
    FC + "fig_20180733_before_after.png": ("antes/depois do piso de intensificação em 20180733",
                                           [(FC + "REPORT.md", "## Measured — TRAIN split")]),
    FC + "measurements.json": ("medições brutas de treino params-12 → params-13",
                               [(FC + "REPORT.md", "## Measured — TRAIN split"), (FW, "## 24. Front C")]),

    # ---------------- frontD ----------------
    FD + "anchoring.json": ("teste de ancoragem artefato vs fase real (C1)", [(FD + "REPORT.md", "## 4. Step 2 — artefact vs real short phase")]),
    FD + "anchoring.txt": ("teste de ancoragem artefato vs fase real (C1)", [(FD + "REPORT.md", "## 4. Step 2 — artefact vs real short phase")]),
    FD + "census.json": ("censo incipient do treino sob params-13", [(FD + "REPORT.md", "## 3. Census — TRAIN")]),
    FD + "census.txt": ("censo incipient do treino sob params-13", [(FD + "REPORT.md", "## 3. Census — TRAIN")]),
    FD + "constant_baseline.json": ("baseline constante para o fim do incipient", [(FD + "REPORT.md", "### 5.1 Divergence from the brief")]),
    FD + "constant_baseline.txt": ("baseline constante para o fim do incipient", [(FD + "REPORT.md", "### 5.1 Divergence from the brief")]),
    FD + "evaluate_params13_train.txt": ("saída do avaliador (treino, params-13)", [(FD + "REPORT.md", "## 5. Evaluator output, verbatim")]),
    FD + "verify_hashes.txt": ("verificação dos hashes antes de medir — PASS", [(FD + "REPORT.md", "## 1. Hash verification")]),
    FD + "fig_*_opening.png": ("figuras da abertura das séries C1 (bruta e filtrada)", [(FD + "REPORT.md", "## 7. Figures")]),

    # ---------------- frontRefusal ----------------
    FR + "classification.json": ("classificação das recusas por causa (M1>M2>M3)", [(FR + "REPORT.md", "## Step 3 — classification by cause")]),
    FR + "classification.txt": ("classificação por causa; contagem do defeito I no conjunto", [(FR + "REPORT.md", "## Step 3 — classification by cause"), (FW, "### (d) Defect I (open)")]),
    FR + "evaluate_params13_train.txt": ("saída do avaliador (treino, params-13)", [(FR + "REPORT.md", "## Step 0 — state check")]),
    FR + "refusal.json": ("caminhos de recusa por série", [(FR + "REPORT.md", "## Step 1 — the refusal paths")]),
    FR + "refusal.txt": ("caminhos de recusa e as seis séries", [(FR + "REPORT.md", "## Step 2 — the six series")]),
    FR + "separability.json": ("separabilidade da recusa por tau", [(FR + "REPORT.md", "## Step 4 — separability")]),
    FR + "separability.txt": ("separabilidade da recusa por tau", [(FR + "REPORT.md", "## Step 4 — separability")]),
    FR + "tau_sweep.json": ("varredura completa de tau: nenhum tau leva o bastante à tolerância", [(FR + "REPORT.md", "### The τ claim, strengthened")]),
    FR + "tau_sweep.txt": ("varredura completa de tau", [(FR + "REPORT.md", "### The τ claim, strengthened")]),
    FR + "fig_*_refusal.png": ("figuras das séries recusadas", [(FR + "REPORT.md", "### Figures")]),

    # ---------------- item19 ----------------
    I19 + "closeout_measurements.txt": ("as três medições de fechamento pedidas na revisão", [(I19 + "REPORT.md", "## 4. Findings recorded in passing")]),
    I19 + "evaluate_params10_train.txt": ("saída do avaliador (treino, params-10)", [(I19 + "REPORT.md", "### 1.1 Scoring (step 2.1)")]),
    I19 + "fig_20160735_params10.png": ("figura de 20160735 sob params-10", [(I19 + "REPORT.md", "## 1. Stage 1")]),
    I19 + "fig_prominence_distributions.png": ("distribuições de proeminência relativa", [(I19 + "REPORT.md", "### 1.3 Relative prominence")]),
    I19 + "fig_tradeoff_pr060_maf090.png": ("o trade-off desenhado", [(I19 + "REPORT.md", "### 2.3 The trade-off, exactly")]),
    I19 + "stage1_baseline.txt": ("baseline constante do estágio 1", [(I19 + "REPORT.md", "### 1.2 Constant baseline")]),
    I19 + "stage2_cells.json": ("grade de 45 células, bruto", [(I19 + "REPORT.md", "## 2. Stage 2 — the 45-cell grid"), (FW, "### (b) Result — gate FAIL")]),

    # ---------------- item20a ----------------
    I20A + "evaluate_params10_train.txt": ("avaliador params-10 (antes)", [(I20A + "REPORT.md", "## P2 / T9")]),
    I20A + "evaluate_params11_train.txt": ("avaliador params-11 (depois)", [(I20A + "REPORT.md", "## Gate verdict")]),
    I20A + "measurements.json": ("medições brutas params-10 vs params-11", [(I20A + "REPORT.md", "`measurements.json` for the raw record")]),

    # ---------------- item20b ----------------
    I20B + "analyse_20b.txt": ("números do relatório do estágio 1 (profundidade dos vales)", [(I20B + "REPORT.md", "## 5. Measurement A"), (FW, "### Stage 1 — does valley depth separate")]),
    I20B + "defectH_watch.txt": ("vigia do defeito H durante o piso de mature", [(I20B + "REPORT_stage2.md", "### Defect H watch")]),
    I20B + "denominator_robustness.txt": ("robustez do denominador de D1", [(I20B + "REPORT_stage2.md", "## 6. Extra measurement 2")]),
    I20B + "depth_table.csv": ("tabela dos vales geradores e suas profundidades", [(I20B + "REPORT.md", "## 5. Measurement A")]),
    I20B + "fig_20160735_before_after.png": ("antes/depois de mature_min_depth em 20160735", [(I20B + "REPORT_stage2.md", "### (a) `20160735` reduces to one block")]),
    I20B + "fig_20205386_before_after.png": ("antes/depois de mature_min_depth em 20205386", [(I20B + "REPORT_stage2.md", "## 4. The gate at `mature_min_depth = 0.80`")]),
    I20B + "gate_stage2.txt": ("gate (a)–(f) do estágio 2 — PASS", [(I20B + "REPORT_stage2.md", "### Gate verdict"), (FW, "### Stage 2 — the rule, implemented anyway")]),
    I20B + "measurements.json": ("dump por série do estágio 1", [(I20B + "REPORT.md", "* `measurements.json` — the full per-series dump.")]),
    I20B + "stage2_measurements.json": ("dump do gate do estágio 2", [(I20B + "REPORT_stage2.md", "### Gate verdict")]),
    I20B + "supplement_20b.txt": ("conteúdo DC da série que alimenta mature; recontagem", [(I20B + "REPORT.md", "### Its mean — and why the brief's inference")]),

    # ---------------- item30 ----------------
    I30 + "census_train_params14.csv": ("censo de treino sob params-14", [(I30 + "REPORT.md", "## Step 3 — train census")]),
    I30 + "evaluate_params14_train_batch.txt": ("avaliador params-14 com lote", [(I30 + "REPORT.md", "## Step 2 — gate (0a)/(0b)")]),
    I30 + "figs_cf/*.png": ("figuras rótulo × params-13 × params-14 × contrafactual (treino)", [(I30 + "REPORT_figs_cf.md", "Figures are in `figs_cf/`"), (FW, "and `figs_cf/`. Each of 8 TRAIN cases")]),
    I30 + "figs_cf_output.txt": ("tabela rótulo × params-14 × contrafactual para os 8 casos", [(I30 + "REPORT_figs_cf.md", "# Item 30 — label × params-13")]),
    I30 + "figs_part3/*.png": ("antes/depois dos 5 adjudicados", [(I30 + "REPORT_part3.md", "- `figs_part3/`: before and after")]),
    I30 + "outside_signal_output.txt": ("as 5 fora do sinal e a variante estreita (medida, não adotada)", [(I30 + "REPORT_part3.md", "## Checkpoint addendum (2026-09-27)")]),
    I30 + "outside_signal.py": ("docstring registra quantas trajetórias swell a regra muda", [(I30 + "REPORT_part3.md", "**R3, the 5 unpredicted tracks.**")]),
    I30 + "part3_eval_params14.txt": ("avaliador params-14 (parte 3)", [(I30 + "REPORT_part3.md", "## Score, params-14 → params-15")]),
    I30 + "part3_eval_params15.txt": ("avaliador params-15 (parte 3)", [(I30 + "REPORT_part3.md", "## Score, params-14 → params-15")]),
    I30 + "part3_measure_output.txt": ("medição da parte 3 (predições R1..)", [(I30 + "REPORT_part3.md", "## Predictions")]),
    I30 + "post_merge_checks_output.txt": ("checagens pós-merge: avaliador e 51 séries idênticos", [(FW, "(`research/labels/diagnostics/item30/post_merge_checks.py`):")]),
    I30 + "prove_defaults_30c.txt": ("30c não muda caminhos default", [(FW, "### Default paths unchanged (`research/labels/diagnostics/item30/prove_defaults_30c.py`")]),
    I30 + "prove_defaults_part3_checkpoint.txt": ("parte 3 não muda caminhos default (checkpoint)", [(I30 + "REPORT_part3.md", "(`prove_defaults_part3_checkpoint.txt`).")]),
    I30 + "prove_defaults_part3_step2.txt": ("parte 3 não muda caminhos default (passo 2)", [(I30 + "REPORT_part3.md", "- `prove_defaults_part3.py`, with outputs")]),
    I30 + "prove_defaults_part3_step3.txt": ("parte 3 não muda caminhos default (passo 3)", [(I30 + "REPORT_part3.md", "`prove_defaults_part3_step3.txt`. The evaluator")]),
    I30 + "separability_criterion.json": ("critério de separabilidade declarado", [(I30 + "REPORT_part2.md", "## Setup")]),
    I30 + "separability_train_output.txt": ("separabilidade no treino: sem separação", [(I30 + "REPORT_part2.md", "## Step 1 — the three candidates on the training series")]),
    I30 + "separability_train_params14.csv": ("tabela de separabilidade por série (params-14)", [(I30 + "REPORT_part2.md", "## Step 1 — the three candidates on the training series")]),

    # ---------------- item31 ----------------
    I31 + "benchmark_swap_mutation.txt": ("mutação: colunas trocadas no teste do benchmark são detectadas", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),
    I31 + "benchmark_swap_mutation_2c.txt": ("mutação repetida na etapa 2c", [(I31 + "DESIGN.md", "## 12. Stage 2c")]),
    I31 + "constant_train.json": ("baseline constante no treino (params-15, defaults, constante)", [(I31 + "DESIGN.md", "## 5. Stage-1 criterion")]),
    I31 + "constant_train.txt": ("baseline constante no treino", [(I31 + "DESIGN.md", "## 5. Stage-1 criterion")]),
    I31 + "exposure_table.json": ("dados do registro de exposição do TESTE", [(I31 + "DESIGN.md", "## 3. Exposure of the TEST series")]),
    I31 + "fix_use_filter_false_before.json": ("registro antes do fix use_filter=False (crash)", [(I31 + "DESIGN.md", "* The before-fix record is `fix_use_filter_false_before.json`.")]),
    I31 + "fix_use_filter_false_after.json": ("registro depois do fix use_filter=False", [("CHANGELOG.md", "### Fixed — `process_vorticity(use_filter=False)` crashed")]),
    I31 + "fix_use_filter_false_equivalence.txt": ("o que rodava antes do fix roda igual; o que quebrava agora roda", [("CHANGELOG.md", "crashed now run (`research/labels/diagnostics/item31/fix_use_filter_false_equivalence.txt`).")]),
    I31 + "fix_use_filter_false_equivalence.py": ("docstring descreve o defeito encontrado", [("CHANGELOG.md", "### Fixed — `process_vorticity(use_filter=False)` crashed")]),
    I31 + "footprint_train.json": ("pegada do default novo no treino", [(I31 + "DESIGN.md", "## 7. Default filtering — proposal")]),
    I31 + "footprint_train.txt": ("pegada do default novo no treino", [(I31 + "DESIGN.md", "## 7. Default filtering — proposal")]),
    I31 + "future_work_numbers.json": ("números do registro do item 31, regenerados", [(FW, "## 31. params-15 as the package default")]),
    I31 + "gate_2a.txt": ("gate 2a (remoção de params-1..14) — PASS", [(I31 + "DESIGN.md", "## 10. Stage 2a")]),
    I31 + "gate_2b.json": ("gate 2b (defaults viram params-15)", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),
    I31 + "gate_2b.txt": ("gate 2b", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),
    I31 + "p15_expected_digest.txt": ("digest esperado após a etapa 2 (layout front_b)", [(I31 + "DESIGN.md", "## 6. Stage-2 equivalence gate")]),
    I31 + "reachability_train.json": ("alcançabilidade no treino", [(I31 + "DESIGN.md", "## 2. Reachability on TRAIN")]),
    I31 + "reachability_train.txt": ("alcançabilidade no treino", [(I31 + "DESIGN.md", "## 2. Reachability on TRAIN")]),
    I31 + "sidebar_table_2c.json": ("barra lateral derivada da assinatura (2c)", [(I31 + "DESIGN.md", "## 12. Stage 2c")]),
    I31 + "sidebar_table_2c.md": ("barra lateral derivada da assinatura (2c)", [(I31 + "DESIGN.md", "## 12. Stage 2c")]),
    I31 + "stage1_output.json": ("a rodada única de pontuação do estágio 1 — PASS", [(FW, "### Stage 1 — the single scoring run")]),
    I31 + "stage1_output.txt": ("a rodada única de pontuação do estágio 1 — PASS", [(FW, "### Stage 1 — the single scoring run")]),
    I31 + "stage1_smoke_train.txt": ("smoke test do pontuador no treino", [(I31 + "DESIGN.md", "## 9. Stage 1, part A — the freeze")]),
    I31 + "stale_scripts.json": ("lista dos scripts que param de rodar", [(I31 + "DESIGN.md", "## 10. Stage 2a")]),
    I31 + "suite_2a.txt": ("suíte após 2a", [(I31 + "DESIGN.md", "## 10. Stage 2a")]),
    I31 + "suite_2b_final.txt": ("suíte após 2b", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),
    I31 + "suite_2b_measure.txt": ("suíte com os defaults novos antes de tocar testes (falhas esperadas)", [(I31 + "DESIGN.md", "**Measurement** (new defaults, before any test was touched)")]),
    I31 + "suite_2b_prefix.txt": ("suíte no prefixo de 2b (uma falha, a do use_filter=False)", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),
    I31 + "suite_2c.txt": ("suíte após 2c", [(FW, "### Stage 2c — the sidebar opens with the package defaults")]),
    I31 + "test_label_census.json": ("censo declarado dos rótulos de TESTE (contagens)", [(I31 + "DESIGN.md", "## 4. Label-only census of the TEST split")]),
    I31 + "train_sequences_2b.md": ("sequências de treino 2.0.0 vs novo no checkpoint 2b", [(I31 + "DESIGN.md", "## 11. Stage 2b")]),

    # ---------------- incipient_plateau ----------------
    IP + "incipient_measurements.csv": ("medições incipient por trajetória (caracterização)", [(IP + "REPORT_incipient_characterisation.md", "# 1. The four paths of `find_incipient_period`")]),
    IP + "summary_tables.txt": ("tabelas-resumo da caracterização", [(IP + "REPORT_incipient_characterisation.md", "# 6. Summary of findings")]),
    IP + "incipient_smoothing_real_rel0.csv": ("rel(t0) nas trajetórias reais por janela de suavização", [(IP + "REPORT_incipient_smoothing.md", "# 4. The real tracks say something different")]),
    IP + "incipient_smoothing_sweep.csv": ("varredura de janela/critério da sonda incipient", [(IP + "REPORT_incipient_smoothing.md", "# 3. Ranking by number")]),
    IP + "incipient_smoothing_tables.txt": ("tabelas da varredura de suavização", [(IP + "REPORT_incipient_smoothing.md", "# 5. Summary")]),
    IP + "geometric_vs_plateau.csv": ("fronteira incipient por caso, reais e sintéticos: geometric vs plateau vs verdade de projeto", []),
    IP + "gen_geometric_vs_plateau.py": ("gerador do checkpoint visual geometric×plateau (produz geometric_vs_plateau.csv); nenhum relatório o cita", []),

    # ---------------- inert_params ----------------
    IN + "inertia_matrix.csv": ("matriz de inércia parâmetro × config", [(IN + "REPORT_inertia_sweep.md", "## Gate (b) — classification")]),
    IN + "inertia_matrix_full.csv": ("matriz de inércia completa (com derivados)", [(FW, "### (b) F(iii)")]),
    IN + "sweep_summary.txt": ("resumo da varredura de inércia", [(IN + "REPORT_inertia_sweep.md", "were correctly flagged INERT by the sweep")]),
    IN + "sweep_derived_summary.txt": ("resumo da varredura derivada", [(IN + "REPORT_inertia_sweep.md", "## Methodology corrections")]),
}

# Reports that are consolidated: their finding line (qualitative) per file or glob.
REPORT_FINDING = {
    "*": "relatório de frente fechada (achados, previsões, veredito)",
}

# --------------------------------------------------------------------------- #
# Section (a): per stale script — where its result is recorded. Keyed by the
# front directory; the anchors are resolved like the others.
STALE_RESULT = {
    DIAG + "frontA_reverify/": [(FW, "## 27. Front A′"), (FAR + "REPORT.md", "### Attribution")],
    DIAG + "frontC/":          [(FW, "## 24. Front C"), (FC + "REPORT.md", "## Measured — TRAIN split")],
    DIAG + "frontD/":          [(FW, "## 25. Front D"), (FD + "REPORT.md", "## 3. Census — TRAIN")],
    DIAG + "frontRefusal/":    [(FW, "## 26. Front \"incipient refusal\""), (FR + "REPORT.md", "## Step 3 — classification by cause")],
    DIAG + "front_b/":         [(FW, "## 19. Front B"), (FB + "ADDENDUM_part1b.md", "## 1. The `distance` sweep")],
    DIAG + "item19/":          [(FW, "### (b) Result — gate FAIL"), (I19 + "REPORT.md", "## 5. Gate verdict")],
    DIAG + "item20a/":         [(FW, "### 20(a) — `mature_amplitude_fraction`"), (I20A + "REPORT.md", "## Gate verdict")],
    DIAG + "item20b/":         [(FW, "## 22. Front 20(b)"), (I20B + "REPORT_stage2.md", "### Gate verdict")],
    DIAG + "item30/":          [(FW, "## 30. Plateau overwriting"), (I30 + "REPORT_part3.md", "## Closing record (2026-09-27)")],
    DIAG + "item31/":          [(FW, "## 31. params-15 as the package default"), (I31 + "DESIGN.md", "## 9. Stage 1, part A — the freeze")],
    "research/labels/swell_item30/": [(FW, "## 30. Plateau overwriting"), ("research/labels/swell_item30/README.md", "# Item 30 — the swell batch")],
}

# --------------------------------------------------------------------------- #
# Section (b): proposals for LIVE (non-diagnostics) references to params-1..14.
# Default for historical records and closed-front diagnostics is decided by rule
# in make_manifest.py; these are the live files, per file:line range.
P114_LIVE = {
    "CHANGELOG.md": ("manter", "entradas de CHANGELOG narram a história das configs; não carregam arquivo"),
    "cyclophaser/determine_periods.py": ("manter", "docstring: fato histórico (configs anteriores à regra) — não carrega arquivo"),
    "research/inert_params/REPORT_inertia_sweep.md": ("manter", "relatório histórico (consolidar no Passo 2)"),
    "research/labels/README.md": ("manter", "tabela de proveniência das configs removidas (histórico com hashes)"),
    "research/labels/split.yaml": ("manter", "CONGELADO — não reescrever"),
    "research/labels/swell_item30/README.md": ("manter", "registro histórico (recebe só nota de correspondência)"),
    "research/labels/swell_item30/adjudicate_item30.py": ("recuperar de 33ea489", "script de proveniência de dados; load_config('params-14') não roda na ponta"),
    "research/labels/swell_item30/draw_batch.py": ("manter", "`groups_params11.yaml` é nome de arquivo de dados congelado + texto de proveniência"),
    "research/labels/swell_item30/freeze_validation_batch.py": ("manter", "texto de proveniência; não carrega config"),
    "research/labels/swell_item30/transcribe_groups.py": ("manter", "texto de proveniência + nome do arquivo congelado"),
    "research/snapshots/README.md": ("manter", "comparação histórica, já aponta a recuperação via 33ea489"),
    "tests/test_app_distance_removed.py": ("manter", "YAML inline com o valor de params-9 — instrumento congelado embutido"),
    "tests/test_benchmark_apptest.py": ("manter", "comentários históricos do item 31"),
    "tests/test_intensification_min_depth.py": ("migrar", "linhas 69-71: comentário diz sincronizar com arquivo removido por teste que não existe mais (hoje test_params15_yaml_matches_this_module)"),
    "tests/test_item30_spare_intensification.py": ("manter", "params-14 reconstruído em memória como params-15 − 1 chave (instrumento congelado derivado)"),
    "tests/test_layer_inspector.py": ("manter", "comentários históricos"),
    "tests/test_reclassify_index0.py": ("manter", "valores de params-13 embutidos inline (PARAMS_13_PV) — instrumento congelado"),
    "tools/calibration_app/README.md": ("manter", "aponta a recuperação; linha 279 é histórico"),
    "tools/calibration_app/app.py": ("manter", "comentários/ajuda de compatibilidade com YAMLs antigos que usuários ainda importam"),
    "tools/calibration_app/benchmark_core.py": ("migrar", "docstring/comentário afirmam que item19_core.CONFIG fixa params-10 — CONFIG não existe mais; 'onze configurações' também"),
    "tools/calibration_app/benchmark_tab.py": ("manter", "ajuda do anotador histórico (bad_cases_count de YAMLs antigos)"),
    "tools/calibration_app/layer_inspector.py": ("migrar", "docstrings dizem que a fidelidade é fixada 'sob params-14'; o teste hoje usa params-15"),
}

# --------------------------------------------------------------------------- #
# Section (c): params-15 VIVA / HISTÓRICA — rules by path (first match wins).
P15_CLASS = [
    ("docs/future_work.md", "HISTÓRICA", "registro de itens fechados"),
    ("research/labels/split.yaml", "HISTÓRICA", "congelado"),
    ("research/labels/swell_item30/README.md", "HISTÓRICA", "registro do item 30"),
    (DIAG + "item31/param_table.json", "HISTÓRICA*", "artefato do item 31, mas lido por teste vivo (só `rows`) — conferir no Passo 1"),
    (DIAG, "HISTÓRICA", "registro/diagnóstico de frente"),
    ("CHANGELOG.md", "VIVA", "seção [Unreleased]"),
    ("", "VIVA", "código, teste, app ou doc de usuário"),
]

# --------------------------------------------------------------------------- #
# Section (d): nature of each boundary_padding hit, by (file, line-range) rules.
# (file, first, last, nature). Lines outside every range fall to "uso/passagem".
BP_NATURE = [
    ("CHANGELOG.md", 20, 32, "tabela do CHANGELOG [Unreleased] (2.0.0 → agora)"),
    ("CHANGELOG.md", 500, 699, "texto de CHANGELOG — entradas antigas [Unreleased→2.0.0]; histórico da mudança zero→reflect"),
    ("CHANGELOG.md", 700, 9999, "texto de CHANGELOG — releases publicados"),
    ("cyclophaser/determine_periods.py", 423, 423, "ASSINATURA process_vorticity (default)"),
    ("cyclophaser/determine_periods.py", 1369, 1369, "ASSINATURA determine_periods (default)"),
    ("cyclophaser/determine_periods.py", 434, 442, "docstring (process_vorticity: nota de defaults calibrados)"),
    ("cyclophaser/determine_periods.py", 876, 884, "docstring (get_periods: nota de defaults calibrados — cita o default de process_vorticity)"),
    ("cyclophaser/determine_periods.py", 1404, 1412, "docstring (determine_periods: nota de defaults calibrados)"),
    ("cyclophaser/determine_periods.py", 1040, 1046, "docstring (get_periods, incipient_method: 'reflect' como regime calibrado)"),
    ("cyclophaser/determine_periods.py", 1517, 1523, "docstring (determine_periods, incipient_method: idem)"),
    ("cyclophaser/determine_periods.py", 480, 600, "docstring (process_vorticity: parâmetro + boundary_padding note)"),
    ("cyclophaser/determine_periods.py", 1450, 1490, "docstring (determine_periods: parâmetro + nota)"),
    ("cyclophaser/determine_periods.py", 610, 625, "validação / texto de DeprecationWarning"),
    ("cyclophaser/lanczos_filter.py", 1, 70, "comentário de módulo"),
    ("cyclophaser/lanczos_filter.py", 80, 80, "ASSINATURA _convolve_same (default próprio)"),
    ("cyclophaser/lanczos_filter.py", 159, 159, "ASSINATURA lanczos_filter (default próprio)"),
    ("cyclophaser/lanczos_filter.py", 216, 216, "ASSINATURA lanczos_bandpass_filter (default próprio)"),
    ("cyclophaser/lanczos_filter.py", 81, 240, "docstring / corpo"),
    ("docs/future_work.md", 1, 99999, "registro histórico"),
    ("docs/usage.rst", 1, 9999, "texto de doc de usuário"),
    ("research/labels/configs/cyclophaser_params-15.yaml", 1, 999, "YAML (params-15, conteúdo intacto)"),
    ("tools/calibration_app/README.md", 1, 9999, "texto do README do app"),
    ("tools/calibration_app/app.py", 216, 216, "app: default lido da ASSINATURA (derivado)"),
    ("tools/calibration_app/app.py", 1439, 1439, "app: fallback LITERAL de preset (\"reflect\")"),
    ("tools/calibration_app/app.py", 1584, 1584, "app: widget inicializado de _DEFAULTS (derivado da assinatura)"),
    ("tools/calibration_app/app.py", 3120, 3160, "app: texto de ajuda (aba Documentation)"),
    ("tools/calibration_app/app.py", 1620, 1630, "app: texto de ajuda do widget"),
    ("tools/calibration_app/benchmark_core.py", 1, 9999, "app/benchmark: detecção de YAML pré-fix (ausência da chave)"),
    ("tools/calibration_app/benchmark_tab.py", 1, 9999, "app/benchmark: texto"),
]

# --------------------------------------------------------------------------- #
# 0.3 Branches: proposed destination + reason (judgement). Anything not listed
# falls to the rule in make_manifest.py (merged → apagar; else decidir).
BRANCH = {
    # Destinations follow Danilo's approved decisions (MANIFEST "Decisões aprovadas",
    # numbered there). "tag de arquivo" = annotated tag archive/* at the tip before the
    # remote branch may go; deleting a remote branch needs per-branch authorisation (Passo 6).
    "develop-v2.1": ("manter", "branch de desenvolvimento"),
    "master": ("manter", "branch de release"),
    "chore/repo-cleanup": ("manter", "branch desta frente (em andamento)"),
    "diag/front-b-distance-inert": ("tag de arquivo", "patch-equivalente a develop (git cherry só '-'), mas NÃO ancestral: o hash 491a5d0 é citado nos registros (ver 'hashes citados') e só resolve enquanto houver uma ref"),
    "diag/series-sha256-mismatch": ("tag de arquivo", "decisão 6: branch de registro — script + relatório do item 10 só existem aqui; future_work cita a branch"),
    "feat/label-tab-toplevel": ("tag de arquivo", "decisão 1: 3 re-rotulagens de treino (0c63145) NÃO são recuperadas; entram como pendência aberta no documento único (Passo 2); código da UI superado"),
    "fix/idx0-boundary-extremum-type": ("tag de arquivo", "decisão 6: branch de registro — artefatos de Front A (6060c6d) contra os quais o item 27 comparou; commit marcado NÃO MERGEAR"),
    "fix/inspector-min-depth-params": ("tag de arquivo", "decisão 5: superada por 52ecb04 (item 30a)"),
    "joss-submission": ("tag de arquivo", "decisão 6: branch de registro — fonte do artigo JOSS (paper/); nada disso está em develop"),
    "research/item20c-duration-ratio": ("tag de arquivo (após Passo 2)", "decisão 5: o texto do item 23 de future_work só existe aqui; entra no documento único (Passo 2), depois tag"),
    "research/v3-topology-proxy": ("tag de arquivo (após Passo 2)", "decisão 5: o texto do item 18 de future_work só existe aqui; entra no documento único (Passo 2), depois tag"),
}

# --------------------------------------------------------------------------- #
# Findings held by files that are KEPT (not removed): informative only.
KEEP_FINDING = {
    "docs/future_work.md": "registro canônico de todas as frentes (achados, gates, decisões)",
    "CHANGELOG.md": "mudanças de comportamento por versão, com tabelas de defaults",
    "research/labels/README.md": "tabela de proveniência/hash das configs, removidas incluídas",
    "research/labels/swell_item30/README.md": "registro do lote swell (seleção, marcas, exposição)",
    "research/snapshots/README.md": "comparação snapshot publicado × params-11",
    DIAG + "front_b/default_behaviour_sha256.txt": "histórico do digest default por commit/ambiente",
    DIAG + "item31/param_table.json": "tabela defaults do pacote × params-15 (item 31)",
    DIAG + "item31/recovery_table.md": "de onde recuperar cada params-1..14 (hash verificado)",
    DIAG + "item31/recovery_table.json": "idem, dados",
    "research/labels/front_g/front_g_synthetic_deviations.md": "desvio detectado − rótulo por fronteira sintética",
    "research/labels/swell_item30/adjudicate_item30_output.txt": "log da adjudicação dos 5 rótulos (demais blocos idênticos)",
    "research/labels/swell_item30/freeze_validation_batch_output.txt": "log do congelamento do lote de validação",
}

# Per-line overrides for section (b) (file:line -> (proposal, reason)).
P114_LINE = {
    "CHANGELOG.md:232": ("migrar", "[Unreleased] aponta `configs/cyclophaser_params-14.yaml`, que não existe mais na árvore — apontar recovery_table/33ea489 ou params-track"),
    "CHANGELOG.md:288": ("migrar", "[Unreleased] aponta `configs/cyclophaser_params-13.yaml`, que não existe mais — idem"),
}
