#!/usr/bin/env python
"""Passo 3, R4 — references to removed paths in LIVE files (definitions: passo3/PREVISOES.md).

    python research/cleanup/passo3/live_refs.py

The removal list is passo3/removed_files.txt when it exists (after the removal),
otherwise it is regenerated by removal_list.py. Live files are read from the
working tree: cyclophaser/, tests/, tools/, README.md, CLAUDE.md, docs/*.rst,
research/labels/README.md, research/labels/swell_item30/README.md and every
kept .py under research/ (research/cleanup/ excluded).

A mention is the removed file's full repo path, or — for a live file in the
same directory — its bare file name. Not counted as a live reference:
* the archived form `archive/research-diagnostics-pre-cleanup:<path>`;
* in a .py file, the name of a file the script itself WRITES, wherever the
  name appears in that script (docstring, print, the write itself). A file is
  written by the script when its name occurs on a line that holds a write call
  (to_csv, to_json, write_text, write_bytes, savefig, json.dump,
  open(..., "w"/"a")), or on a line assigning a name that such a write call in
  the same file uses. Rerunning the script recreates the file. Listed apart in
  own_outputs.txt.

Writes live_refs.json, live_refs.txt and own_outputs.txt next to it; exit 1 if
a live reference remains.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
TAG = "archive/research-diagnostics-pre-cleanup"
WRITE = re.compile(r"\.(to_csv|to_json|write_text|write_bytes|savefig)\(|json\.dump\(|open\([^)]*['\"][wa]b?['\"]")
ASSIGN = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")


def removed() -> list[str]:
    f = HERE / "removed_files.txt"
    if f.exists():
        return [l for l in f.read_text().splitlines() if l]
    sys.path.insert(0, str(HERE))
    from removal_list import removal_list
    return removal_list()


def live_files(rem: set[str]) -> list[str]:
    tracked = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True).split()
    out = []
    for t in tracked:
        if t in rem or t.startswith("research/cleanup/") or not (ROOT / t).exists():
            continue
        if (t.startswith(("cyclophaser/", "tests/", "tools/"))
                or t in ("README.md", "CLAUDE.md", "research/labels/README.md", "research/labels/swell_item30/README.md")
                or (t.startswith("docs/") and t.endswith(".rst"))
                or (t.startswith("research/") and t.endswith(".py"))):
            out.append(t)
    return out


def main():
    rem = set(removed())
    by_dir: dict[str, set[str]] = {}
    for r in rem:
        by_dir.setdefault(str(Path(r).parent), set()).add(Path(r).name)
    refs, own = [], []
    for f in live_files(rem):
        try:
            lines = (ROOT / f).read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        write_lines = [l for l in lines if WRITE.search(l)] if f.endswith(".py") else []
        writes = set()                                     # basenames this script writes
        if f.endswith(".py"):
            for line in lines:
                m = ASSIGN.match(line)
                if WRITE.search(line) or (m and any(re.search(r"\b" + m.group(1) + r"\b", w) for w in write_lines)):
                    writes |= {Path(r).name for r in rem if Path(r).name in line}
        for i, line in enumerate(lines, 1):
            clean = line.replace(TAG + ":", "\0")          # archived form resolves by the tag
            hits = sorted(r for r in rem if r in clean and ("\0" + r) not in clean)
            local = by_dir.get(str(Path(f).parent), set())
            hits += sorted(str(Path(f).parent / n) for n in local
                           if re.search(r"(?<![\w./-])" + re.escape(n) + r"(?![\w])", clean)
                           and str(Path(f).parent / n) not in hits)
            for r in hits:
                is_output = f.endswith(".py") and Path(r).name in writes \
                    and str(Path(r).parent) == str(Path(f).parent)
                (own if is_output else refs).append(dict(file=f, line=i, removed=r, text=line.strip()[:160]))
    out = dict(removed=len(rem), live_references=len(refs), own_outputs=len(own), refs=refs, own=own)
    (HERE / "live_refs.json").write_text(json.dumps(out, indent=1, ensure_ascii=False))
    (HERE / "live_refs.txt").write_text(
        f"live references to removed paths: {len(refs)}\n" + "".join(f"{r['file']}:{r['line']} -> {r['removed']}\n" for r in refs))
    (HERE / "own_outputs.txt").write_text(
        f"# outputs written by the kept script itself (not live references): {len(own)}\n"
        + "".join(f"{r['file']}:{r['line']} -> {r['removed']}\n" for r in own))
    print(f"removed {len(rem)}; live references {len(refs)}; own outputs {len(own)}")
    for r in refs:
        print(f"  {r['file']}:{r['line']} -> {r['removed']}")
    sys.exit(1 if refs else 0)


if __name__ == "__main__":
    main()
