#!/usr/bin/env python
"""Passo 3, R4 — references to removed paths in LIVE files (definitions: passo3/PREVISOES.md).

    python research/cleanup/passo3/live_refs.py [LABEL]   # outputs LABEL.json/.txt/_own_outputs.txt

The removal list is passo3/removed_files.txt when it exists (after the removal),
otherwise it is regenerated by removal_list.py. Live files are read from the
working tree: cyclophaser/, tests/, tools/, README.md, CLAUDE.md, docs/*.rst,
research/labels/README.md, research/labels/swell_item30/README.md and every
kept .py under research/ (research/cleanup/ excluded).

A mention (corrected scanner, same frozen definition): the line contains any
suffix of the removed path with 2 or more components (`item31/DESIGN.md`,
`diagnostics/item31/DESIGN.md`, the full path), or the bare file name when no
file tracked at HEAD carries that name. The FIRST version of this scanner only
matched the full path (and the bare name inside the same directory), which let
partial-path mentions through; see passo3/RELATORIO.md. Not counted:
* the archived form `archive/research-diagnostics-pre-cleanup:<path>`;
* in a .py file, the name of a file the script itself WRITES, wherever the
  name appears in that script (docstring, print, the write itself). A file is
  written by the script when its name occurs on a line that holds a write call
  (to_csv, to_json, write_text, write_bytes, savefig, json.dump,
  open(..., "w"/"a")), or on a line assigning a name that such a write call in
  the same file uses. Rerunning the script recreates the file. Listed apart in
  own_outputs.txt.

Writes live_refs.json, live_refs.txt and own_outputs.txt next to it; exit 1 if
a live reference remains.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
TAG = "archive/research-diagnostics-pre-cleanup"
WRITE = re.compile(r"\.(to_csv|to_json|write_text|write_bytes|savefig)\(|json\.dump\(|open\([^)]*['\"][wa]b?['\"]")
ASSIGN = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")


def removed() -> list[str]:
    """Paths of the removal list that are NOT in the tree now (a file restored
    later, e.g. by commit 14, is no longer a removed path)."""
    f = HERE / "removed_files.txt"
    if f.exists():
        tracked = set(subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True).split())
        return [l for l in f.read_text().splitlines() if l and l not in tracked]
    sys.path.insert(0, str(HERE))
    from removal_list import removal_list
    return removal_list()


def live_files(rem: set[str]) -> list[str]:
    tracked = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True).split()
    out = []
    for t in tracked:
        if t in rem or t.startswith("research/cleanup/") or not (ROOT / t).exists():
            continue
        if (t.startswith(("cyclophaser/", "tests/", "tools/"))
                or t in ("README.md", "CLAUDE.md", "research/labels/README.md", "research/labels/swell_item30/README.md")
                or (t.startswith("docs/") and t.endswith(".rst"))
                or (t.startswith("research/") and t.endswith(".py"))):
            out.append(t)
    return out


def mention_patterns(rem: set[str], head_names: set[str]) -> dict[str, list[re.Pattern]]:
    """Per removed path: every suffix of 2+ components (the full path included),
    plus the bare file name when no file tracked at HEAD carries that name."""
    pats = {}
    for r in rem:
        parts = r.split("/")
        forms = ["/".join(parts[i:]) for i in range(len(parts) - 1)]      # suffixes with >= 2 components
        if parts[-1] not in head_names:
            forms.append(parts[-1])
        pats[r] = [re.compile(r"(?<![\w.-])" + re.escape(x) + r"(?![\w])") for x in forms]
    return pats


ARCHIVED = re.compile(re.escape(TAG) + r":\S+")


def main():
    label = sys.argv[1] if len(sys.argv) > 1 else "live_refs"
    rem = set(removed())
    head = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True).split()
    pats = mention_patterns(rem, {Path(t).name for t in head})
    refs, own = [], []
    for f in live_files(rem):
        try:
            lines = (ROOT / f).read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        fdir = Path(f).parent
        written = set()        # path components (relative to the script's dir) the script itself writes
        if f.endswith(".py"):
            write_lines = [l for l in lines if WRITE.search(l)]
            for line in lines:
                m = ASSIGN.match(line)
                if WRITE.search(line) or (m and any(re.search(r"\b" + m.group(1) + r"\b", w) for w in write_lines)):
                    for r in rem:
                        rp = Path(r)
                        if fdir in rp.parents:
                            for comp in rp.relative_to(fdir).parts:
                                if comp in line:
                                    written.add(comp)
        for i, line in enumerate(lines, 1):
            clean = ARCHIVED.sub(" ", line)             # the archived form resolves by the tag
            for r in sorted(rem):
                if not any(pt.search(clean) for pt in pats[r]):
                    continue
                rp = Path(r)
                is_output = (f.endswith(".py") and fdir in rp.parents
                             and any(comp in written for comp in rp.relative_to(fdir).parts))
                (own if is_output else refs).append(dict(file=f, line=i, removed=r, text=line.strip()[:160]))
    out = dict(removed=len(rem), live_references=len(refs), own_outputs=len(own),
               files_with_references=len({r["file"] for r in refs}), refs=refs, own=own)
    (HERE / f"{label}.json").write_text(json.dumps(out, indent=1, ensure_ascii=False))
    (HERE / f"{label}.txt").write_text(
        f"live references to removed paths: {len(refs)} in {out['files_with_references']} files\n"
        + "".join(f"{r['file']}:{r['line']} -> {r['removed']}\n" for r in refs))
    (HERE / f"{label}_own_outputs.txt").write_text(
        f"# outputs written by the kept script itself (not live references): {len(own)}\n"
        + "".join(f"{r['file']}:{r['line']} -> {r['removed']}\n" for r in own))
    print(f"removed {len(rem)}; live references {len(refs)} in {out['files_with_references']} files; own outputs {len(own)}")
    for r in refs:
        print(f"  {r['file']}:{r['line']} -> {r['removed']}")
    sys.exit(1 if refs else 0)


if __name__ == "__main__":
    main()
