#!/usr/bin/env python
"""Passo 4, Fase B rodada 1 (item 4) — hourly vorticity series available in the
repository for the usage-guide example, with their origin (read-only).

    python research/cleanup/passo4/hourly_series_options.py   # writes hourly_series_options.md next to it

Candidates: every tracked .csv under tests/ and the package example file. For
each: its role in research/labels/split.yaml (train / test / batch / spent
validation / not labelled). Files in a TEST split are listed by name only and
NOT opened (the test split is spent). For the others: the time column's step,
the number of points, whether a min_max_zeta_850 column exists, and the commit
that added the file (origin).
"""
import subprocess
from collections import Counter
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[3]
split = yaml.safe_load((ROOT / "research/labels/split.yaml").read_text())
role = {}
for i in split.get("train", []):
    role[str(i)] = "train (top-level split)"
for i in split.get("test", []):
    role[str(i)] = "TEST (top-level split)"
for b, d in split.get("batches", {}).items():
    for k in ("train", "test", "validation"):
        for i in d.get(k, []) or []:
            role[str(i)] = f"{'TEST' if k == 'test' else k} (batch {b}{', ' + d['role'] if d.get('role') else ''})"


def git(*a):
    return subprocess.check_output(["git", *a], cwd=ROOT, text=True).strip()


files = [f for f in git("ls-files", "tests", "cyclophaser/example_data").split() if f.endswith(".csv")]
rows = []
for f in sorted(files):
    stem = Path(f).stem
    r = role.get(stem, "not in split.yaml")
    origin = git("log", "--diff-filter=A", "--format=%h %ad %s", "--date=short", "--", f).splitlines()
    origin = origin[-1][:90] if origin else "?"
    if "TEST" in r:
        rows.append((f, r, "not opened", "", "", origin))
        continue
    df = pd.read_csv(ROOT / f, sep=None, engine="python", nrows=5000)
    tcol = next((c for c in df.columns if c.lower() == "time"), df.columns[0])
    try:
        t = pd.to_datetime(df[tcol], format="mixed")
        step = Counter((t.diff().dropna()).astype("timedelta64[s]").astype(int) // 60).most_common(1)[0][0]
        step = f"{step} min"
    except Exception:
        step = "no datetime"
    rows.append((f, r, step, len(df), "yes" if "min_max_zeta_850" in df.columns else "no", origin))
out = ["# Hourly series available for the usage example (generated by hourly_series_options.py)\n",
       "| file | role (split.yaml) | step | points | `min_max_zeta_850` | added by |", "|---|---|---|---|---|---|"]
out += [f"| `{a}` | {b} | {c} | {d} | {e} | {g} |" for a, b, c, d, e, g in rows]
n = Counter(r[1].split(" (")[0] for r in rows)
out += ["", f"Totals by role: {dict(n)}."]
(Path(__file__).with_name("hourly_series_options.md")).write_text("\n".join(out) + "\n")
print("\n".join(out[-1:]))


# --- candidates for the example: hourly, real, train, with min_max_zeta_850 ----------------
import importlib  # noqa: E402
import sys  # noqa: E402
import warnings  # noqa: E402

warnings.simplefilter("ignore")
importlib.import_module("cyclophaser.determine_periods")
DP = sys.modules["cyclophaser.determine_periods"]
cand = [r for r in rows if r[2] == "60 min" and r[4] == "yes" and r[1].startswith("train")]
lines = ["", "## Candidates: hourly, real, in a TRAIN split, with `min_max_zeta_850`\n",
         f"{len(cand)} files. Phase sequence under the package defaults (`determine_periods(series)`), "
         "used only to pick an illustrative example; nothing is scored.\n",
         "| file | points | phase sequence (defaults) | clean |", "|---|---|---|---|"]
clean = []
for f, *_ in cand:
    s = pd.read_csv(ROOT / f, sep=";", parse_dates=[0], index_col=0)["min_max_zeta_850"]
    p = DP.determine_periods(s)["periods"]
    seq = [x for i, x in enumerate(p) if i == 0 or x != p.iloc[i - 1]]
    ok = seq[:4] == ["incipient", "intensification", "mature", "decay"] and len(seq) <= 5 and len(set(seq)) == len(seq)
    clean.append((f, len(s), seq)) if ok else None
    lines.append(f"| `{f}` | {len(s)} | {' → '.join(map(str, seq))} | {'yes' if ok else ''} |")
lines += ["", f"Clean (incipient → intensification → mature → decay, optionally → one more phase, no repeat): "
          f"{len(clean)} of {len(cand)}."]
with open(Path(__file__).with_name("hourly_series_options.md"), "a") as fh:
    fh.write("\n".join(lines) + "\n")
print("\n".join(lines[-1:]))
for f, n, seq in clean:
    print(" ", f, n, seq)
