#!/usr/bin/env python
"""Passo 4, 16f (1) — doi_metadata.md from the raw responses saved next to it
(nothing typed): doi_crossref_raw.json (api.crossref.org/works/<doi>),
doi_org_apa_raw.txt and doi_org_bibtex_raw.bib (doi.org content negotiation).

    python research/cleanup/passo4/make_doi_metadata.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DOI = "10.21105/joss.07363"
raw = json.loads((HERE / "doi_crossref_raw.json").read_text())
m = raw["message"]
apa = (HERE / "doi_org_apa_raw.txt").read_text().strip()
bib = (HERE / "doi_org_bibtex_raw.bib").read_text().strip()
authors = [f"{a.get('given', '')} {a.get('family', '')}".strip() for a in m["author"]]
year = m["published"]["date-parts"][0][0]
fields = [
    ("title", m["title"][0]),
    ("authors", "; ".join(authors)),
    ("year", year),
    ("published (date-parts)", m["published"]["date-parts"][0]),
    ("journal", m["container-title"][0]),
    ("volume", m.get("volume")),
    ("issue (number)", m.get("issue")),
    ("page / article number", m.get("page") or m.get("article-number")),
    ("publisher", m.get("publisher")),
    ("DOI", m["DOI"]),
    ("URL", m["URL"]),
]
# the formatted citation is built ONLY from the Crossref fields above, and must equal doi.org's APA text
built = (", ".join(f"{a['family']}, {' '.join(p[0] + '.' for p in a['given'].split())}" for a in m["author"][:-1])
         + f", & {m['author'][-1]['family']}, {' '.join(p[0] + '.' for p in m['author'][-1]['given'].split())}"
         + f" ({year}). {m['title'][0]}. {m['container-title'][0]}, {m['volume']}({m['issue']}), "
         + f"{m.get('page') or m.get('article-number')}. https://doi.org/{m['DOI']}")
out = [f"# DOI {DOI} — metadata (generated by make_doi_metadata.py)\n",
       "Sources, saved raw next to this file: Crossref REST API "
       f"(`https://api.crossref.org/works/{DOI}`, `doi_crossref_raw.json`, status `{raw['status']}`), and doi.org "
       "content negotiation (`Accept: text/x-bibliography; style=apa` → `doi_org_apa_raw.txt`; "
       "`Accept: application/x-bibtex` → `doi_org_bibtex_raw.bib`).\n",
       "| field (Crossref) | value |", "|---|---|"]
out += [f"| {k} | {v} |" for k, v in fields]
out += ["", "## Formatted citation\n", "doi.org (APA, verbatim):\n", f"> {apa}\n",
        "Rebuilt from the Crossref fields above:\n", f"> {built}\n",
        f"Identical: **{built == apa}**.\n", "## BibTeX (doi.org, verbatim)\n", "```bibtex", bib, "```"]
(HERE / "doi_metadata.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
