#!/usr/bin/env python
"""Passo 4, commit 16e — intermediate build measurement (D3 itself is measured in
Phase C). Reads the three build logs of passo4/ and the built docs/_build/html
(api.html); writes build_16e.md. Nothing typed.

    python research/cleanup/passo4/make_build_16e.py
"""
import ast
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]


def j(n):
    return json.loads((HERE / n).read_text())


def head(n):
    return re.search(r"^HEAD: ([0-9a-f]{40})", (HERE / n).read_text(), re.M).group(1)[:7]


B = [("before 16d (autodoc, no napoleon)", "build_rtd_raw"),
     ("16d, without napoleon", "build_16d_no_napoleon_raw"),
     ("16d + napoleon (16e)", "build_16e_raw")]
html = (ROOT / "docs/_build/html/api.html").read_text()
a, i = html.find('<dl class="py function">'), html.find('<dl class="field-list">')
dp = (ROOT / "cyclophaser/determine_periods.py").read_text().splitlines()
fn = next(n for n in ast.walk(ast.parse("\n".join(dp))) if isinstance(n, ast.FunctionDef) and n.name == "determine_periods")
sig = [x.arg for x in fn.args.args + fn.args.kwonlyargs]
rendered = set(re.findall(r'param (\w+)<span class="colon">', html))
left = [n for n, l in enumerate(dp, 1) if "**Must match the length of `series**`" in l]
out = ["# Commit 16e — build with napoleon (intermediate measurement; generated by make_build_16e.py)\n",
       "Environment: the venv that mirrors `.readthedocs.yml` (docs/requirements.txt + `pip install .`), reinstalled "
       "from the tree at each HEAD. D3 is measured in Phase C, not here.\n",
       "| build | HEAD | errors | warnings | log |", "|---|---|---|---|---|"]
for label, n in B:
    r = j(f"{n}.json")
    out.append(f"| {label} | `{head(n + '.txt')}` | {r['errors']} | {r['warnings']} | `{n}.txt` |")
out += ["", "## What remains\n"]
for label, n in B[1:]:
    out += [f"* {label}: " + "; ".join(f"`{w.split(': WARNING: ')[-1]}`" for w in j(f'{n}.json')['warning_lines'])]
out += [f"* The remaining warning is the unmatched bold in the `x` parameter: `cyclophaser/determine_periods.py:"
        f"{left[0] if left else '?'}` (\"**Must match the length of `series**`\"). It was the first warning of the "
        "build before 16d (docstring line 45 → this line). `rtd_map.md` attributed it to `:1481-1482`, which was "
        "wrong; 16d edited `:1481-1482` (harmless) and left this line.",
       "",
       "## Napoleon rendering\n",
       f"* The Google-style `Args:` become a field list (`param …` / `type …`): {len(rendered)} of the "
       f"{len(sig)} parameters of `determine_periods` get a field; without one: {sorted(set(sig) - rendered)} "
       "(the `Args:` section of the docstring does not document them).",
       "* The fields are NOT grouped into Sphinx's \"Parameters\" block: the docstring opens with an rst section title "
       "(\"Defaults (item 31, then C1 …)\" with an underline), so everything after it, the field list included, sits "
       "inside a `<section>` and is no longer a direct child of the function's content, which is all Sphinx's "
       "doc-field transform reads. HTML tags between the function and its field list: "
       f"{re.findall(r'<(section|blockquote)\b', html[a:i])}.",
       "* Fixing it is a docstring edit in `cyclophaser/` (for example the title turned into a paragraph or a "
       "napoleon `Note:` section) and was not done here."]
(HERE / "build_16e.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
