#!/usr/bin/env python
"""Passo 4, 16f (4) — what LICENSE, setup.py and docs/license.rst say today,
literal, with file:line (README.md added as a fourth place that states it).

    python research/cleanup/passo4/make_license_texts.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]


def lines(f):
    return (ROOT / f).read_text().splitlines()


def quote(f, nums):
    L = lines(f)
    return [f"| `{f}:{n}` | `{L[n - 1].rstrip()}` |" for n in nums]


lic = lines("LICENSE")
lic_nums = [i for i, l in enumerate(lic, 1)
            if i <= 2 or re.search(r"any later version|version 3 of the|How to Apply These Terms", l)]
setup = lines("setup.py")
cls_start = next(i for i, l in enumerate(setup, 1) if "classifiers=[" in l)
cls_end = next(i for i in range(cls_start, len(setup) + 1) if setup[i - 1].strip() == "],")
setup_nums = [i for i, l in enumerate(setup, 1) if re.search(r"\blicense", l)] + list(range(cls_start, cls_end + 1))
classifiers = [l.strip().strip('",') for l in setup[cls_start:cls_end - 1]]
rst = lines("docs/license.rst")
readme_nums = [i for i, l in enumerate(lines("README.md"), 1) if re.search(r"licen[cs]e", l, re.I)]

out = ["# Licence texts today (generated by make_license_texts.py)\n",
       "## `LICENSE`\n",
       f"{len(lic)} lines. The header lines, and every line that mentions version 3 or \"any later version\":\n",
       "| file:line | text |", "|---|---|"] + quote("LICENSE", lic_nums)
how = next(i for i in lic_nums if "How to Apply" in lic[i - 1])
out += ["", f"Lines from `LICENSE:{how}` on are the GPL's own \"How to Apply These Terms\" template, i.e. a notice for "
        "an author to copy into source files. They are not a statement by this project. The "
        "\"any later version\" lines before it are section 14 of the licence text.\n",
        "## `setup.py`\n", "| file:line | text |", "|---|---|"] + quote("setup.py", setup_nums)
out += ["", f"Licence classifier among the classifiers: "
        f"{[c for c in classifiers if c.startswith('License')] or 'none'} (classifiers: {classifiers}).\n",
        "## `docs/license.rst` (whole file)\n", "| file:line | text |", "|---|---|"]
out += [f"| `docs/license.rst:{i}` | {l.rstrip() or '(blank)'} |" for i, l in enumerate(rst, 1)]
out += ["", "## `README.md` (lines that mention the licence)\n", "| file:line | text |", "|---|---|"]
out += quote("README.md", readme_nums)
(HERE / "license_texts.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
