#!/usr/bin/env python
"""Passo 4, 16f (3) — the Python versions the CI actually tests, read from the CI
configuration files tracked in the repository (nothing typed).

    python research/cleanup/passo4/make_ci_python.py
"""
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
tracked = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True).split()
ci_files = [f for f in tracked if re.match(r"(\.circleci/|\.github/workflows/|\.gitlab-ci|\.travis|azure-pipelines|tox\.ini|noxfile)", f)]
out = ["# CI — Python versions tested (generated by make_ci_python.py)\n",
       f"CI configuration files tracked: {', '.join(f'`{f}`' for f in ci_files) or 'none'} "
       f"(searched: `.circleci/`, `.github/workflows/`, GitLab, Travis, Azure, tox, nox).\n"]
for f in ci_files:
    lines = (ROOT / f).read_text().splitlines()
    job = None
    rows = []
    for i, l in enumerate(lines, 1):
        m = re.match(r"^  (\w+):\s*$", l)          # a job key, two spaces under `jobs:`
        if m:
            job = m.group(1)
        mi = re.search(r"image:\s*(\S*python\S*)", l)
        if mi:
            rows.append((job, i, mi.group(1)))
    out += [f"## `{f}`\n", "| job | line | image | Python |", "|---|---|---|---|"]
    out += [f"| `{j}` | `{f}:{i}` | `{img}` | {re.search(r'python:([0-9.]+)', img).group(1)} |" for j, i, img in rows]
    test_cmd = [(i, l.strip()) for i, l in enumerate(lines, 1) if re.search(r"command:.*-m pytest", l)]
    out += ["", "Test command(s): " + "; ".join(f"`{f}:{i}` `{c}`" for i, c in test_cmd)]
    versions = sorted({re.search(r"python:([0-9.]+)", img).group(1) for _, _, img in rows})
    tested = sorted({re.search(r"python:([0-9.]+)", img).group(1) for j, _, img in rows if j and "test" in j
                     and "publish" not in j})
    out += ["", f"Python versions in the file: {versions}. Versions in the job that runs the tests: {tested}. "
            "There is no version matrix."]
out += ["", "## Observation (read from the configuration, not measured on CI)\n",
        "The test job installs the wheel and then runs `python -m pytest` from the checkout root. `python -m` puts the "
        "current directory first on `sys.path`, so `import cyclophaser` in the tests can resolve to the checked-out "
        "source tree rather than to the installed wheel. The comment at the top of the file says the job checks what a "
        "`pip install cyclophaser` user gets. Whether it does was not measured here."]
(HERE / "ci_python.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
