"""Item 31, stage 2a, step 1 — recovery table for the configs removed by this front.

Danilo's decision (2026-09-28, DESIGN.md §8): params-1 … params-14 are REMOVED
from research/labels/configs/; params-15 stays. Before anything is deleted,
this script records, for every file to be removed:

    file | sha256 | last commit in which it exists | command to recover it

"Last commit in which it exists" is HEAD at generation time, which must be the
PARENT of the commit that deletes the files (asserted by gate_2a.py). Each row
is VERIFIED here: `git show <commit>:<path>` is hashed and must equal both the
working-tree file and the sha256 recorded in research/labels/README.md's table.

Output: recovery_table.md (pasted into DESIGN.md §10), recovery_table.json.
Run: python -P research/labels/diagnostics/item31/recovery_table.py
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
CONFIGS = REPO / "research" / "labels" / "configs"
README = REPO / "research" / "labels" / "README.md"


def git(*a, binary=False):
    r = subprocess.run(["git", *a], cwd=REPO, capture_output=True, check=True)
    return r.stdout if binary else r.stdout.decode().strip()


def main() -> None:
    assert not git("status", "--porcelain", "--untracked-files=no", "--", str(CONFIGS)), \
        "configs/ has uncommitted changes"
    head = git("rev-parse", "HEAD")
    readme = README.read_text()
    rows = []
    for n in range(1, 15):
        rel = f"research/labels/configs/cyclophaser_params-{n}.yaml"
        p = REPO / rel
        assert p.is_file(), rel
        sha = hashlib.sha256(p.read_bytes()).hexdigest()
        shown = hashlib.sha256(git("show", f"{head}:{rel}", binary=True)).hexdigest()
        assert shown == sha, f"{rel}: git show {shown} != working tree {sha}"
        m = re.search(rf"`cyclophaser_params-{n}\.yaml` \| `([0-9a-f]{{64}})`", readme)
        assert m and m.group(1) == sha, f"{rel}: README sha256 disagrees"
        rows.append({"file": rel, "sha256": sha, "commit": head,
                     "recover": f"git show {head[:12]}:{rel} > {Path(rel).name}"})
    assert (CONFIGS / "cyclophaser_params-15.yaml").is_file()

    md = ["| file | sha256 | last commit in which it exists | recover with |",
          "|---|---|---|---|"]
    for r in rows:
        md.append(f"| `{Path(r['file']).name}` | `{r['sha256']}` | `{r['commit'][:12]}` | "
                  f"`{r['recover']}` |")
    text = "\n".join(md)
    (HERE / "recovery_table.md").write_text(
        f"Generated by `recovery_table.py` at HEAD `{head}`; every row verified: "
        "`git show` hash == working-tree hash == README table hash.\n\n" + text + "\n")
    (HERE / "recovery_table.json").write_text(json.dumps({"head": head, "rows": rows}, indent=2))
    print(f"HEAD {head}\n{text}")


if __name__ == "__main__":
    main()
