"""Item 31, stage 2a, step 2 — scripts that stop running when params-1..14 leave the repo.

Closed fronts' diagnostic scripts are NOT migrated (Danilo's decision): they are
records of what was run, and they reproduce from the commit where the configs
still exist. This script only LISTS them, from the tracked tree, by STATIC
evidence read with `ast` — no script is run. Prose that merely mentions a
config (docstrings, notes, labels inside longer strings) is NOT evidence; only:

* a string literal that IS a removed config path or file name
  (`…/cyclophaser_params-N.yaml` or `cyclophaser_params-N.yaml`, N <= 14);
* a string literal that IS a removed config's short name, `"params-N"` —
  how the item-30/31 scripts name a config for `load_config`;
* `item19_core`'s default config: `load_config()` with no argument, or
  `.CONFIG`, in a script that imports item19_core (both removed).

Scope: every tracked .py under research/ except research/labels/*.py (migrated).

Output: stale_scripts.md, stale_scripts.json.
Run: python -P research/labels/diagnostics/item31/stale_scripts.py
"""

from __future__ import annotations

import ast
import json
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
RECOVERY = "33ea489358d9"

# Static hits checked by reading the code and found NOT to load a removed config.
VERIFIED_NOT_STALE = {
    "research/labels/diagnostics/item19/item19_core.py":
        "migrated in 2a: its only hit is REMOVED_CONFIG, the path it names in the "
        "error that load_config() now raises; pair_by_overlap/MARGIN unchanged",
    "research/labels/diagnostics/item31/exposure_table.py":
        "the \"params-N\" literals are the `config` column of EVENTS (text); "
        "the script loads no config",
}

FILE_RX = re.compile(r"^(?:.*/)?cyclophaser_params-(\d+)\.yaml$")
NAME_RX = re.compile(r"^params-(\d+)$")


def _docstring_ids(tree) -> set:
    ids = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if body and isinstance(body[0], ast.Expr) and isinstance(
                    getattr(body[0], "value", None), ast.Constant):
                ids.add(id(body[0].value))
    return ids


def evidence(src: str) -> list[str]:
    tree = ast.parse(src)
    docs = _docstring_ids(tree)
    uses_item19 = "item19_core" in src
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str) \
                and id(node) not in docs:
            for why, rx in (("removed file", FILE_RX), ("removed config name", NAME_RX)):
                m = rx.match(node.value.strip())
                if m and int(m.group(1)) <= 14:
                    out.append((node.lineno, f"{why} params-{m.group(1)} (line {node.lineno})"))
        if uses_item19 and isinstance(node, ast.Call):
            f = node.func
            name = f.attr if isinstance(f, ast.Attribute) else getattr(f, "id", "")
            if name == "load_config" and not node.args and not node.keywords:
                out.append((node.lineno, f"item19_core default config: load_config() "
                                         f"(line {node.lineno})"))
        if uses_item19 and isinstance(node, ast.Attribute) and node.attr == "CONFIG":
            out.append((node.lineno, f"item19_core default config: .CONFIG (line {node.lineno})"))
    return [w for _, w in sorted(set(out))]


def main() -> None:
    files = subprocess.run(["git", "ls-files", "research/*.py", "research/**/*.py"], cwd=REPO,
                           capture_output=True, text=True, check=True).stdout.split()
    hits = {}
    for f in sorted(set(files)):
        if Path(f).parent == Path("research/labels") or f.endswith("stale_scripts.py"):
            continue
        reasons = evidence((REPO / f).read_text())
        if reasons and f not in VERIFIED_NOT_STALE:
            hits[f] = reasons

    md = [f"Generated by `stale_scripts.py`. {len(hits)} tracked script(s) stop running once "
          "params-1..14 leave `research/labels/configs/`. None is migrated; each reproduces "
          f"from commit `{RECOVERY}` (e.g. `git worktree add ../cp-{RECOVERY} {RECOVERY}` and run "
          "it there — mind item 27's worktree-shadowing rule: assert `cyclophaser.__file__`).",
          "", "| script | evidence (first 3) |", "|---|---|"]
    for f, rs in hits.items():
        md.append(f"| `{f}` | {'; '.join(rs[:3])}{' …' if len(rs) > 3 else ''} |")
    md += ["", "Static hits verified NOT to stop running (read, not run):", ""]
    md += [f"* `{f}` — {why}" for f, why in VERIFIED_NOT_STALE.items()]
    (HERE / "stale_scripts.md").write_text("\n".join(md) + "\n")
    (HERE / "stale_scripts.json").write_text(json.dumps(hits, indent=2))
    print("\n".join(md))


if __name__ == "__main__":
    main()
