#!/usr/bin/env python
"""Front 20(c) stage 1 - anchor analysis over the facts measured by
item20c_measure.py. Reads JSON only; runs no detector.

Three anchor definitions, all declared before the measurement:
  A) anchor = block generated by the valley of greatest D1
  B) anchor = block of greatest duration
  C) anchor = block matched to a manual label (DIAGNOSTIC ONLY - not
     implementable, because in production there is no label)

For each non-anchor block, ratio = duration(block) / duration(anchor), under the
declared convention duration = end - start + 1. A proportional floor r rejects a
block when ratio < r. The anchor itself is never rejected by construction.
"""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
F = json.loads((OUT / "item20c_facts.json").read_text())


def anchor_A(blocks):
    return max(range(len(blocks)), key=lambda i: (blocks[i]["D1"] if blocks[i]["D1"] is not None else -1))


def anchor_B(blocks):
    return max(range(len(blocks)), key=lambda i: blocks[i]["duration"])


def anchor_C(blocks):
    m = [i for i, b in enumerate(blocks) if b["matched_label"] is not None]
    return m[0] if m else None


def fmt(x, n=4):
    return "-" if x is None else (f"{x:.{n}f}" if isinstance(x, float) else str(x))


lines = []
W = lines.append

W("# Front 20(c) stage 1 - anchor tables")
W("")
W(f"config sha256: {F['config_sha256']}")
W(f"numpy {F['numpy']}  scipy {F['scipy']}  pandas {F['pandas']}")
W(f"duration convention: {F['duration_convention']}")
W("")

multi = [r for r in F["series"] if r["n_blocks"] > 1]
W(f"## Series with more than one mature block under params-12: {len(multi)}")
W("")
for pop in ("real", "synthetic"):
    sub = [r for r in multi if r["pop"] == pop]
    W(f"### {pop} ({len(sub)} of {sum(1 for r in F['series'] if r['pop']==pop)} in train)")
    W("")
    W("| series | block | start | end | dur | valley | D1 | label matched | d_start | d_end | ratio/A | ratio/B | ratio/C |")
    W("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in sub:
        b = r["blocks"]
        ia, ib, ic = anchor_A(b), anchor_B(b), anchor_C(b)
        for i, blk in enumerate(b):
            def ratio(ai):
                if ai is None:
                    return None
                return blk["duration"] / b[ai]["duration"]
            tags = "".join(t for t, cond in (("A", i == ia), ("B", i == ib), ("C", i == ic)) if cond)
            W(f"| {r['id']} | {i}{' ['+tags+']' if tags else ''} | {blk['start']} | {blk['end']} "
              f"| {blk['duration']} | v{blk['valley_idx']} | {fmt(blk['D1'])} "
              f"| {'-' if blk['matched_label'] is None else 'L'+str(blk['matched_label'])} "
              f"| {fmt(blk['d_start'])} | {fmt(blk['d_end'])} "
              f"| {fmt(ratio(ia),3)} | {fmt(ratio(ib),3)} | {fmt(ratio(ic),3)} |")
        W(f"| {r['id']} | *labels* | {r['lab_mature']} unsure={r['lab_unsure']} | | | | | | | | | | |")
    W("")

W("## Anchor divergence")
W("")
W("| series | A (max D1) | B (max duration) | C (label-matched) | A==B | A==C | B==C |")
W("|---|---|---|---|---|---|---|")
diverge = []
for r in multi:
    b = r["blocks"]
    ia, ib, ic = anchor_A(b), anchor_B(b), anchor_C(b)
    same_ab = ia == ib
    same_ac = (ic is not None and ia == ic)
    same_bc = (ic is not None and ib == ic)
    if not (same_ab and same_ac and same_bc):
        diverge.append(r["id"])
    cdesc = "NONE" if ic is None else f"block {ic} ({b[ic]['start']},{b[ic]['end']})"
    W(f"| {r['id']} | block {ia} ({b[ia]['start']},{b[ia]['end']}) "
      f"| block {ib} ({b[ib]['start']},{b[ib]['end']}) "
      f"| {cdesc} "
      f"| {'yes' if same_ab else 'NO'} | {'yes' if same_ac else 'NO'} | {'yes' if same_bc else 'NO'} |")
W("")
W(f"Series where the anchors do not all agree: {diverge}")
W("")

# ---- the floor band -------------------------------------------------------
W("## Usable band for a proportional floor r")
W("")
W("A floor r rejects a non-anchor block when ratio < r. For each anchor")
W("definition, the constraints are:")
W("  - r must EXCEED the ratio of every spurious (label-unmatched) block that")
W("    must be removed;")
W("  - r must NOT exceed the ratio of any label-matched block.")
W("")
for name, fn in (("A", anchor_A), ("B", anchor_B), ("C", anchor_C)):
    W(f"### Anchor {name}")
    spurious, matched, unreachable = [], [], []
    for r in F["series"]:
        b = r["blocks"]
        if len(b) < 2:
            continue
        ai = fn(b)
        if ai is None:
            unreachable.append((r["id"], "no label-matched block: anchor C undefined"))
            continue
        for i, blk in enumerate(b):
            if i == ai:
                if blk["matched_label"] is None:
                    unreachable.append((r["id"], f"block {i} is spurious AND is the anchor -> can never be removed"))
                continue
            ratio = blk["duration"] / b[ai]["duration"]
            (spurious if blk["matched_label"] is None else matched).append((r["id"], i, ratio))
    if spurious:
        need = max(x[2] for x in spurious)
        W(f"- spurious non-anchor blocks (ratio): " + ", ".join(f"{s}#{i}={v:.3f}" for s, i, v in sorted(spurious, key=lambda x: -x[2])))
        W(f"  -> to remove ALL of them, r > {need:.4f}")
    else:
        W("- no spurious non-anchor block exists under this anchor")
        need = None
    if matched:
        cap = min(x[2] for x in matched)
        W(f"- label-matched non-anchor blocks (ratio): " + ", ".join(f"{s}#{i}={v:.3f}" for s, i, v in sorted(matched, key=lambda x: x[2])))
        W(f"  -> to preserve ALL of them, r <= {cap:.4f}")
    else:
        W("- no label-matched non-anchor block exists under this anchor")
        cap = None
    if need is not None and cap is not None:
        W(f"- BAND: ({need:.4f}, {cap:.4f}] -> {'NON-EMPTY' if need < cap else 'EMPTY'}")
    for sid, why in unreachable:
        W(f"- UNREACHABLE: {sid}: {why}")
    W("")

(OUT / "item20c_tables.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))


# =========================================================================== #
# Gate of stage 1, evaluated criterion by criterion. Declared before the
# measurement; anchor C does not count toward the verdict.
# =========================================================================== #
gate_lines = []
G = gate_lines.append
G("")
G("## Stage-1 gate, criterion by criterion")
G("")

by_id = {r["id"]: r for r in F["series"]}
SYNTH = [r["id"] for r in F["series"] if r["pop"] == "synthetic"]


def evaluate(anchor_name, fn):
    """For each candidate floor r, which blocks does it reject?"""
    res = {}
    # every ratio that occurs is a candidate breakpoint; a floor only matters
    # through which side of each ratio it falls on
    ratios = set()
    for r in F["series"]:
        b = r["blocks"]
        if len(b) < 2:
            continue
        ai = fn(b)
        if ai is None:
            continue
        for i, blk in enumerate(b):
            if i != ai:
                ratios.add(blk["duration"] / b[ai]["duration"])
    # probe just above each ratio, plus a value above them all
    probes = sorted({x + 1e-9 for x in ratios} | {max(ratios) + 1.0}) if ratios else []

    for r_floor in probes:
        removed, kept_spurious = [], []
        cut_matched = []
        for rec in F["series"]:
            b = rec["blocks"]
            if len(b) < 2:
                continue
            ai = fn(b)
            if ai is None:
                continue
            for i, blk in enumerate(b):
                if i == ai:
                    if blk["matched_label"] is None:
                        kept_spurious.append((rec["id"], i, "anchor"))
                    continue
                ratio = blk["duration"] / b[ai]["duration"]
                if ratio < r_floor:
                    removed.append((rec["id"], i, blk["matched_label"]))
                    if blk["matched_label"] is not None:
                        cut_matched.append((rec["id"], i))
                elif blk["matched_label"] is None:
                    kept_spurious.append((rec["id"], i, "above floor"))
        res[r_floor] = dict(removed=removed, cut_matched=cut_matched,
                            kept_spurious=kept_spurious)
    return res


for anchor_name, fn in (("A (max D1)", anchor_A), ("B (max duration)", anchor_B)):
    G(f"### Anchor {anchor_name}")
    G("")
    ev = evaluate(anchor_name, fn)

    # (a) both spurious blocks of 20205386 removed
    b5386 = by_id["20205386"]["blocks"]
    ai = fn(b5386)
    spur5386 = [i for i, blk in enumerate(b5386) if blk["matched_label"] is None]
    anchor_is_spurious = ai in spur5386
    ok_a_any = False
    for r_floor, d in ev.items():
        rem = {i for s, i, _ in d["removed"] if s == "20205386"}
        if set(spur5386) <= rem:
            ok_a_any = True
            break
    G(f"- **(a)** remove both spurious blocks of 20205386: "
      f"anchor is block {ai} "
      f"({'SPURIOUS - can never be removed' if anchor_is_spurious else 'label-matched'}); "
      f"spurious blocks = {spur5386}. -> **{'PASS' if ok_a_any else 'FAIL'}**")

    # candidate floors that satisfy (b), (c), (d)
    survivors = []
    for r_floor, d in sorted(ev.items()):
        if d["cut_matched"]:
            continue                                   # (b) violated
        rem_ids = {s for s, _, _ in d["removed"]}
        b3947 = by_id["20203947"]["blocks"]
        a3947 = fn(b3947)
        removed_3947 = {i for s, i, _ in d["removed"] if s == "20203947"}
        if removed_3947:                               # (c) strict-loose: keep both blocks
            continue
        if any(s in SYNTH for s, _, _ in d["removed"]):  # (d)
            continue
        survivors.append((r_floor, d))

    if survivors:
        best = survivors[-1][1]
        # State the band in FLOOR terms, not probe terms: a floor r is
        # cost-free iff it exceeds the ratio of every block it must remove and
        # does not exceed the ratio of any label-matched non-anchor block.
        rem_ratios, keep_ratios = [], []
        for rec in F["series"]:
            b = rec["blocks"]
            if len(b) < 2:
                continue
            ai = fn(b)
            if ai is None:
                continue
            for i, blk in enumerate(b):
                if i == ai:
                    continue
                ratio = blk["duration"] / b[ai]["duration"]
                if (rec["id"], i, blk["matched_label"]) in best["removed"]:
                    rem_ratios.append(ratio)
                elif blk["matched_label"] is not None:
                    keep_ratios.append(ratio)
        lo = max(rem_ratios) if rem_ratios else 0.0
        hi = min(keep_ratios) if keep_ratios else float("inf")
        G(f"- **(b)/(c)/(d)** cost-free floors exist: r in ({lo:.4f}, {hi:.4f}]")
        rem_ids = sorted({s for s, _, _ in best["removed"]})
        G(f"  - at the widest such floor, blocks removed: {best['removed']}")
        G(f"  - series improved: {rem_ids}")
        G(f"  - **(e)** generalises beyond 20205386: "
          f"**{'PASS' if len([s for s in rem_ids if s != '20205386']) >= 1 else 'FAIL'}** "
          f"(other series helped: {[s for s in rem_ids if s != '20205386']})")
    else:
        G("- **(b)/(c)/(d)** no floor satisfies all three")
        G("- **(e)** not reachable")
    G("")

G("### Verdict")
G("")
G("The gate requires (a)-(e) to hold together for at least one of anchors A or B.")
G("(a) fails under both, so the stage-1 verdict is **FAIL** regardless of the rest.")

(OUT / "item20c_tables.md").write_text(
    (OUT / "item20c_tables.md").read_text() + "\n".join(gate_lines) + "\n")
print("\n".join(gate_lines))
